import { Language, SimulationScenario } from '../types/aran';

export const localizedVoicePhrases: Record<
  string,
  Record<Language, string>
> = {
  NORMAL: {
    ta: 'லக்ஷ்மி அம்மா, உங்கள் உடல்நலம் மற்றும் சென்சார் அளவீடுகள் அனைத்தும் இயல்பான நிலையில் உள்ளன.',
    hi: 'लक्ष्मी अम्मा, आपके सभी स्वास्थ्य और सेंसर मानक सामान्य स्थिति में हैं।',
    ml: 'ലക്ഷ്മി അമ്മ, താങ്കളുടെ എല്ലാ ആരോഗ്യ സൂചകങ്ങളും സാധാരണ നിലയിലാണ്.',
    te: 'లక్ష్మి అమ్మ, మీ అన్ని ఆరోగ్య సూచికలు సాధారణ స్థితిలో ఉన్నాయి.',
    kn: 'ಲಕ್ಷ್ಮಿ ಅಮ್ಮ, ನಿಮ್ಮ ಎಲ್ಲಾ ಆರೋಗ್ಯ ಸ್ಥಿತಿಗಳು ಸಾಮಾನ್ಯ ಸ್ಥಿತಿಯಲ್ಲಿವೆ.',
    gu: 'લક્ષ્મી અમ્મા, તમારા બધા સ્વાસ્થ્ય પરિમાણો સામાન્ય સ્થિતિમાં છે.',
    fr: 'Bonjour Lakshmi Amma, tous vos paramètres de santé sont normaux.',
    en: 'Lakshmi Amma, all your health vitals and sensor readings are within normal baseline range.',
    tanglish: 'Lakshmi Amma, ungal health vitals and sensor readings ellam normal baseline la irukku.',
  },
  HIGH_BP: {
    ta: 'கவனம்: இரத்த அழுத்த அளவீடு 158/98 ஆக உயர்ந்துள்ளது. கவிதாவிற்கு தகவல் அனுப்பப்பட்டது.',
    hi: 'ध्यान दें: रक्तचाप 158/98 तक बढ़ गया है। देखभालकर्ता कविता को सूचित कर दिया गया है।',
    ml: 'ശ്രദ്ധിക്കുക: രക്തസമ്മർദ്ദം 158/98 ആയി ഉയർന്നിരിക്കുന്നു. കവിതയെ അറിയിച്ചു.',
    te: 'గమనిక: రక్తపోటు 158/98కి పెరిగింది. సంరక్షకురాలికి సమాచారం పంపబడింది.',
    kn: 'ಗಮನಿಸಿ: ರಕ್ತದೊತ್ತಡ 158/98 ಕ್ಕೆ ಹೆಚ್ಚಾಗಿದೆ. ಆರೈಕೆದಾರರಿಗೆ ಮಾಹಿತಿ ನೀಡಲಾಗಿದೆ.',
    gu: 'ધ્યાન આપો: બ્લડ પ્રેશર 158/98 સુધી વધી ગયું છે. કેરગીવર કવિતાને જાણ કરી છે.',
    fr: 'Attention: Tension artérielle élevée à 158/98 mmHg. Aidant prévenu.',
    en: 'High blood pressure reading: 158 over 98. Caregiver verification recommended.',
    tanglish: 'Kavanam: Blood pressure 158/98 ah high ah irukku. Kavitha ku alert anupiyachu.',
  },
  HEAT_WARNING: {
    ta: 'அறை வெப்பநிலை 38.6 டிகிரி செல்சியஸ். வெப்ப எச்சரிக்கை! சிறிது தண்ணீர் குடித்து ஓய்வெடுங்கள்.',
    hi: 'कमरे का तापमान 38.6 डिग्री सेल्सियस है। कृपया पानी पिएं और ठंडी जगह पर आराम करें।',
    ml: 'മുറിയിലെ താപനില 38.6 ഡിഗ്രി സെൽഷ്യസ് ആണ്. ചൂട് മുന്നറിയിപ്പ്! ദയവായി വെള്ളം കുടിക്കുക.',
    te: 'గది ఉష్ణోగ్రత 38.6 డిగ్రీలు ఉంది. వేడి హెచ్చరిక! దయచేసి నీరు త్రాగి విశ్రాంతి తీసుకోండి.',
    kn: 'ಕೋಣೆಯ ಉಷ್ಣಾಂಶ 38.6 ಡಿಗ್ರಿ ಸೆಲ್ಸಿಯಸ್ ಇದೆ. ದಯವಿಟ್ಟು ನೀರು ಕುಡಿದು ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.',
    gu: 'રૂમનું તાપમાન 38.6 ડિગ્રી સેલ્સિયસ છે. કૃપા કરીને પાણી પીઓ અને આરામ કરો.',
    fr: 'Alerte chaleur ambiante à 38.6°C. Veuillez boire de l’eau et vous reposer.',
    en: 'Room heat warning: 38.6 degrees Celsius. Hydration check recommended.',
    tanglish: 'Room temperature 38.6 degree ah irukku. Konjam thanni kudithu rest edunga.',
  },
  MOTION_DETECTED: {
    ta: 'இயக்கம் கண்டறியப்பட்டது. தினசரி நடைப்பயிற்சி படிகள் பதிவு செய்யப்பட்டன.',
    hi: 'गतिविधि का पता चला। दैनिक कदमों की प्रगति दर्ज की गई है।',
    ml: 'ചലനം രേഖപ്പെടുത്തി. ദൈനംദിന നടത്തം രേഖപ്പെടുത്തി.',
    te: 'కదలిక గుర్తించబడింది. రోజువారీ నడక అడుగులు నమోదు చేయబడ్డాయి.',
    kn: 'ಚಟುವಟಿಕೆ ಪತ್ತೆಯಾಗಿದೆ. ದೈನಂದಿನ ನಡಿಗೆಯ ಹೆಜ್ಜೆಗಳು ದಾಖಲಾಗಿವೆ.',
    gu: 'પ્રવૃત્તિ જણાઈ છે. દૈનિક ડગલાં રેકોર્ડ થયા છે.',
    fr: 'Mouvement détecté. Progression de la marche enregistrée.',
    en: 'Natural motion detected. Daily steps and activity progress recorded.',
    tanglish: 'Movement detect aachu. Nadai payirchi steps update aagidichu.',
  },
  POSSIBLE_FALL: {
    ta: 'அவசர எச்சரிக்கை: சாத்தியமான வீழ்ச்சி நிகழ்வு கண்டறியப்பட்டது. தயவுசெய்து சரிபார்க்கவும்!',
    hi: 'आपातकालीन चेतावनी: गिरने की संभावित घटना का पता चला है। कृपया तुरंत जांचें!',
    ml: 'അടിയന്തര മുന്നറിയിപ്പ്: വീഴ്ച സംഭവിച്ചതായി സംശയിക്കുന്നു. ദയവായി പരിശോധിക്കുക!',
    te: 'అత్యవసర హెచ్చరిక: కింద పడిపోయినట్లు గుర్తించబడింది. దయచేసి వెంటనే పరిశీలించండి!',
    kn: 'ತುರ್ತು ಎಚ್ಚರಿಕೆ: ಬಿದ್ದಿರುವ ಸಂಭವನೀಯ ಘಟನೆ ಪತ್ತೆಯಾಗಿದೆ. ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ!',
    gu: 'ઇમરજન્સી ચેતવણી: પતન થવાની સંભાવના જણાય છે. કૃપા કરીને તાત્કાલિક તપાસ કરો!',
    fr: 'Alerte urgente: Événement de chute possible. Veuillez vérifier immédiatement!',
    en: 'Emergency alert: Possible fall event detected. Please check on the senior immediately!',
    tanglish: 'Emergency alert: Possible fall event detect aagi irukku. Senior ah udane check pannunga!',
  },
  WATER_ALERT: {
    ta: 'நீர் அருந்தும் நேரம். லட்சுமி அம்மா, ஒரு டம்ளர் தண்ணீர் குடிக்கிறீர்களா?',
    hi: 'पानी पीने का समय। लक्ष्मी अम्मा, क्या आप एक गिलास पानी पीना चाहेंगी?',
    ml: 'വെള്ളം കുടിക്കാനുള്ള സമയം. ലക്ഷ്മി അമ്മ, ഒരു ഗ്ലാസ് വെള്ളം കുടിക്കാമോ?',
    te: 'నీరు త్రాగాల్సిన సమయం. లక్ష్మి అమ్మ, ఒక గ్లాసు నీరు త్రాగుతారా?',
    kn: 'ನೀರು ಕುಡಿಯುವ ಸಮಯ. ಲಕ್ಷ್ಮಿ ಅಮ್ಮ, ಒಂದು ಲೋಟ ನೀರು ಕುಡಿಯುತ್ತೀರಾ?',
    gu: 'પાણી પીવાનો સમય. લક્ષ્મી અમ્મા, શું તમે એક ગ્લાસ પાણી પીશો?',
    fr: 'Rappel d’hydratation. Lakshmi Amma, voulez-vous un verre d’eau?',
    en: 'Hydration check recommended. Lakshmi Amma, would you like a glass of water?',
    tanglish: 'Hydration check recommended. Lakshmi Amma, oru glass thanni kudikareengala?',
  },
  AMBULANCE_108_DISPATCH: {
    ta: '108 அவசர ஆம்புலன்ஸ் புறப்பட்டுவிட்டது. எட்டு நிமிடங்களில் வந்துவிடும்.',
    hi: '108 आपातकालीन एम्बुलेंस रवाना हो गई है। 8 मिनट में पहुंचेगी।',
    ml: '108 അടിയന്തര ആംബുലൻസ് പുറപ്പെട്ടു. 8 മിനിറ്റിനുള്ളിൽ എത്തും.',
    te: '108 అత్యవసర అంబులెన్స్ బయలుదేరింది. 8 నిమిషాల్లో చేరుకుంటుంది.',
    kn: '108 ತುರ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್ ಹೊರಟಿದೆ. 8 ನಿಮಿಷಗಳಲ್ಲಿ ಬರಲಿದೆ.',
    gu: '108 ઇમરજન્સી એમ્બ્યુલન્સ રવાના થઈ ગઈ છે. 8 મિનિટમાં પહોંચશે.',
    fr: 'Ambulance 108 dépêchée. Arrivée estimée dans 8 minutes.',
    en: '108 Emergency Ambulance dispatched. Estimated arrival in 8 minutes.',
    tanglish: '108 Emergency Ambulance dispatch aagidichu. 8 minutes la vanthudum.',
  },
  SUCCESSFUL_CHECKIN: {
    ta: 'மகிழ்ச்சி லட்சுமி அம்மா! உங்கள் காலை பரிசோதனை வெற்றிகரமாக முடிந்தது.',
    hi: 'बहुत बढ़िया लक्ष्मी अम्मा! आपका सुबह का चेक-इन सफलतापूर्वक पूरा हुआ।',
    ml: 'സന്തോഷം ലക്ഷ്മി അമ്മ! താങ്കളുടെ പ്രഭാത ചെക്ക്-ഇൻ വിജയകരമായി പൂർത്തിയായി.',
    te: 'చాలా మంచిది లక్ష్మి అమ్మ! మీ ఉదయపు చెక్-ఇన్ విజయవంతంగా పూర్తయింది.',
    kn: 'ತುಂಬಾ ಒಳ್ಳೆಯದು ಲಕ್ಷ್ಮಿ ಅಮ್ಮ! ನಿಮ್ಮ ಬೆಳಗಿನ ತಪಾಸಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ.',
    gu: 'ખૂબ સરસ લક્ષ્મી અમ્મા! તમારું સવારનું ચેક-ઇન સફળતાપૂર્વક પૂર્ણ થયું છે.',
    fr: 'Parfait Lakshmi Amma! Votre pointage matinal est validé avec succès.',
    en: 'Thank you Lakshmi Amma! Morning check-in confirmed successfully.',
    tanglish: 'Romba nalladhu Lakshmi Amma! Morning check-in success aagi confirm aachu.',
  },
  MISSED_CHECKIN: {
    ta: 'காலை பரிசோதனை உறுதிப்படுத்தப்படவில்லை. கவிதாவிற்கு நினைவூட்டல் அனுப்பப்பட்டுள்ளது.',
    hi: 'सुबह का चेक-इन पुष्ट नहीं हुआ। बेटी कविता को अलर्ट भेजा गया है।',
    ml: 'പ്രഭാത ചെക്ക്-ഇൻ സ്ഥിരീകരിച്ചില്ല. മകൾ കവിതയ്ക്ക് സന്ദേശം അയച്ചു.',
    te: 'ఉదయపు చెక్-ఇన్ ధృవీకరించబడలేదు. కుమార్తె కవితకు సమాచారం పంపబడింది.',
    kn: 'ಬೆಳಗಿನ ತಪಾಸಣೆ ದೃಢಪಟ್ಟಿಲ್ಲ. ಮಗಳು ಕವಿತಾಗೆ ಮಾಹಿತಿ ಕಳುಹಿಸಲಾಗಿದೆ.',
    gu: 'સવારનું ચેક-ઇન કન્ફર્મ થયું નથી. પુત્રી કવિતાને એલર્ટ મોકલી દીધું છે.',
    fr: 'Pointage matinal non confirmé. Notification d’absence envoyée à Kavitha.',
    en: 'Morning check-in was not confirmed. Notification sent to daughter Kavitha.',
    tanglish: 'Morning check-in confirm aagala. Kavitha ku alert message anupiyachu.',
  },
  LOW_ACTIVITY: {
    ta: 'குறைந்த இயக்கம் கண்டறியப்பட்டது. பராமரிப்பாளர் சரிபார்ப்பு பரிந்துரைக்கப்படுகிறது.',
    hi: 'कम गतिविधि का पता चला। देखभालकर्ता सत्यापन की सिफारिश की जाती है।',
    ml: 'കുറഞ്ഞ ചലനം രേഖപ്പെടുത്തി. പരിചാരക പരിശോധന ശുപാർശ ചെയ്യുന്നു.',
    te: 'తక్కువ కదలిక గుర్తించబడింది. సంరక్షకురాలి పరిశీలన సిఫార్సు చేయబడింది.',
    kn: 'ಕಡಿಮೆ ಚಟುವಟಿಕೆ ಕಂಡುಬಂದಿದೆ. ಆರೈಕೆದಾರರ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ.',
    gu: 'ઓછી પ્રવૃત્તિ જણાઈ છે. કેરગીવર દ્વારા તપાસની ભલામણ છે.',
    fr: 'Faible activité détectée. Vérification de l’aidant recommandée.',
    en: 'Low activity detected during active hours. Caregiver check recommended.',
    tanglish: 'Low activity detect aachu. Caregiver check panna vendiyathu.',
  },
  HIGH_HEART_RATE: {
    ta: 'இருதய துடிப்பு நிமிடத்திற்கு 104 ஆக அதிகரித்துள்ளது. சற்று ஓய்வெடுக்கவும்.',
    hi: 'हृदय गति बढ़कर 104 बीपीएम हो गई है। कृपया थोड़ा आराम करें।',
    ml: 'ഹൃദയമിടിപ്പ് മിനിറ്റിൽ 104 ആയി വർദ്ധിച്ചു. ദയവായി വിശ്രമിക്കുക.',
    te: 'గుండె స్పందన నిమిషానికి 104కి పెరిగింది. కాసేపు విశ్రాంతి తీసుకోండి.',
    kn: 'ಹೃದಯ ಬಡಿತ 104 ಕ್ಕೆ ಏರಿದೆ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.',
    gu: 'હૃદયના ધબકારા વધીને 104 થયા છે. કૃપા કરીને થોડો આરામ કરો.',
    fr: 'Fréquence cardiaque au repos élevée à 104 BPM. Veuillez vous reposer.',
    en: 'Resting heart rate elevated at 104 beats per minute. Caregiver notified.',
    tanglish: 'Heart rate 104 BPM ah high ah irukku. Konjam relax panni rest edunga.',
  },
  LOW_SPO2: {
    ta: 'இரத்த ஆக்சிஜன் அளவு 93 சதவீதமாக குறைந்துள்ளது. சரிபார்க்க பரிந்துரைக்கப்படுகிறது.',
    hi: 'रक्त ऑक्सीजन स्तर 93 प्रतिशत हो गया है। जांच की सिफारिश की जाती है।',
    ml: 'രക്തത്തിലെ ഓക്സിജൻ അളവ് 93 ശതമാനമായി താഴ്ന്നു. പരിശോധന ശുപാർശ ചെയ്യുന്നു.',
    te: 'రక్తంలో ఆక్సిజన్ శాతం 93కి పడిపోయింది. పరిశీలన సిఫార్సు చేయబడింది.',
    kn: 'ರಕ್ತದ ಆಮ್ಲಜನಕ ಮಟ್ಟ 93 ಪ್ರತಿಶತಕ್ಕೆ ಇಳಿದಿದೆ. ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ.',
    gu: 'રક્તમાં ઓક્સિજનનું પ્રમાણ 93 ટકા છે. તપાસ કરવાની ભલામણ છે.',
    fr: 'Taux d’oxygène SpO2 bas à 93%. Vérification recommandée.',
    en: 'SpO2 reading is 93 percent, below personal baseline. Caregiver verification recommended.',
    tanglish: 'Oxygen level 93% ah koranji irukku. Sensor probe and breathing check pannunga.',
  },
  SOS: {
    ta: 'அவசர எஸ்.ஓ.எஸ் இயக்கப்பட்டிவிட்டது! குடும்பத்தினர் மற்றும் 108 ஆம்புலன்ஸுக்கு தகவல் சென்றது.',
    hi: 'आपातकालीन एसओएस सक्रिय हो गया है! परिवार और 108 एम्बुलेंस को सूचित कर दिया गया है।',
    ml: 'അടിയന്തര എസ്.ഒ.എസ് സജീവമാക്കി! കുടുംബത്തെയും 108 ആംബുലൻസിനെയും അറിയിച്ചു.',
    te: 'అత్యవసర SOS ఆన్ చేయబడింది! కుటుంబ సభ్యులకు మరియు 108కి సమాచారం వెళ్ళింది.',
    kn: 'ತುರ್ತು SOS ಸಕ್ರಿಯಗೊಂಡಿದೆ! ಕುಟುಂಬಕ್ಕೆ ಮತ್ತು 108 ಗೆ ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ.',
    gu: 'ઇમરજન્સી SOS સક્રિય થઈ ગયું છે! પરિવાર અને 108 ને એલર્ટ મોકલી દીધું છે.',
    fr: 'Urgence SOS activée! Alerte transmise à la famille et aux secours 108.',
    en: 'Emergency SOS activated! Family network and 108 emergency services alerted.',
    tanglish: 'Emergency SOS activate aagidichu! Family kum 108 ambulance kum alert poyachu.',
  },
  DEVICE_OFFLINE: {
    ta: 'எச்சரிக்கை: அரண் துணை சாதனம் ஆஃப்லைனில் சென்றுவிட்டது.',
    hi: 'चेतावनी: अरण साथी उपकरण ऑफ़लाइन हो गया है।',
    ml: 'മുന്നറിയിപ്പ്: അരണ്‍ ഉപകരണം ഓഫ്‌ലൈനായി.',
    te: 'హెచ్చరిక: అరన్ పరికరం ఆఫ్‌లైన్‌లోకి వెళ్లింది.',
    kn: 'ಎಚ್ಚರಿಕೆ: ಅರಣ್ ಸಾಧನವು ಆಫ್‌ಲೈನ್‌ಗೆ ಹೋಗಿದೆ.',
    gu: 'ચેતવણી: અરણ ડિવાઇસ ઑફલાઇન થઈ ગયું છે.',
    fr: 'Attention: L’appareil ARAN est hors ligne.',
    en: 'Warning: ARAN companion hub has gone offline. Please check power and Wi-Fi.',
    tanglish: 'Warning: ARAN device offline poiduchu. Power and Wi-Fi check pannunga.',
  },
  LOW_BATTERY: {
    ta: 'அரண் பேட்டரி 14 சதவீதம். காந்த சார்ஜிங் டாக்கில் வைக்கவும்.',
    hi: 'अरण की बैटरी 14 प्रतिशत है। कृपया चार्जिंग डॉक पर रखें।',
    ml: 'അരണ്‍ ബാറ്ററി 14 ശതമാനമായി. ദയവായി ചാർജ്ജിംഗ് ഡോക്കിൽ വെയ്ക്കുക.',
    te: 'అరన్ బ్యాటరీ 14 శాతం మాత్రమే ఉంది. దయచేసి ఛార్జింగ్ డాక్‌లో ఉంచండి.',
    kn: 'ಅರಣ್ ಬ್ಯಾಟರಿ 14 ಶೇಕಡಾ ಆಗಿದೆ. ದಯವಿಟ್ಟು ಚಾರ್ಜಿಂಗ್ ಡಾಕ್‌ನಲ್ಲಿ ಇರಿಸಿ.',
    gu: 'અરણ બેટરી 14 ટકા છે. કૃપા કરીને ચાર્જિંગ ડોક પર મૂકો.',
    fr: 'Batterie ARAN faible à 14%. Veuillez la poser sur le socle de charge.',
    en: 'ARAN device battery is low at 14 percent. Please dock for charging.',
    tanglish: 'ARAN battery 14% dhaan irukku. Magnetic dock la vechi charge pannunga.',
  },
  LOCATION_CHANGE: {
    ta: 'எச்சரிக்கை: பாதுகாப்பான எல்லை தாண்டப்பட்டது. கவிதாவிற்கு தகவல் அனுப்பப்பட்டது.',
    hi: 'चेतावनी: सुरक्षित क्षेत्र की सीमा पार हो गई है। देखभालकर्ता को सूचित कर दिया गया है।',
    ml: 'മുന്നറിയിപ്പ്: സുരക്ഷിത അതിർത്തി കടന്നു. പരിചാരകനെ അറിയിച്ചു.',
    te: 'హెచ్చరిక: సురక్షిత సరిహద్దు దాటబడింది. సంరక్షకురాలికి సమాచారం పంపబడింది.',
    kn: 'ಎಚ್ಚರಿಕೆ: ಸುರಕ್ಷಿತ ವಲಯದ ಗಡಿ ದಾಟಲಾಗಿದೆ. ಆರೈಕೆದಾರರಿಗೆ ಮಾಹಿತಿ ನೀಡಲಾಗಿದೆ.',
    gu: 'ચેતવણી: સલામત સીમા ઓળંગી છે. કેરગીવરને જાણ કરવામાં આવી છે.',
    fr: 'Attention: Périmètre de sécurité franchi. L’aidant a été alerté.',
    en: 'Safe zone boundary crossed. Senior location updated and caregiver alerted.',
    tanglish: 'Safe zone boundary cross aagidichu. Location update aagi Kavitha ku alert poyachu.',
  },
};

export const getLocalizedSpeech = (scenario: string, language: Language): string => {
  const phraseGroup = localizedVoicePhrases[scenario];
  if (!phraseGroup) return '';
  return phraseGroup[language] || phraseGroup.en || '';
};
