import { Language } from '../types/aran';

export interface LocalizedMedication {
  id: string;
  name: string;
  dosage: string;
  time: string;
  instructions: string;
  category: string;
}

export interface LocalizedFoodTiming {
  id: string;
  mealName: string;
  scheduledTime: string;
  recommendedDiet: string;
  notes: string;
}

export interface LocalizedFamilyMember {
  id: string;
  name: string;
  relationship: string;
  phone: string;
  address: string;
  notes: string;
}

export interface LocalizedNeighborhoodEmergency {
  id: string;
  name: string;
  type: string;
  phone: string;
  distance: string;
  address: string;
}

export interface LocalizedMedicalReport {
  primaryIllness: string[];
  ongoingTreatments: string[];
  hospitalName: string;
  hospitalAddress: string;
  hospitalEmergencyPhone: string;
  doctorName: string;
  doctorSpecialty: string;
  doctorPhone: string;
  nextFollowUpDate: string;
  bloodGroup: string;
  allergies: string[];
  insuranceProvider: string;
  policyNumber: string;
  tpaHelpline: string;
}

export interface LocalizedLivingArrangement {
  title: string;
  subtitle: string;
  desc: string;
}

export interface LocalizedLoginPage {
  whoAreYou: string;
  seniorPatient: string;
  familyCaregiver: string;
  homeInCharge: string;
  seniorLivingArrangement: string;
  careContext: string;
  withFamily: LocalizedLivingArrangement;
  livingIndependently: LocalizedLivingArrangement;
  withRelatives: LocalizedLivingArrangement;
  withPartner: LocalizedLivingArrangement;
  authTitle: string;
  mobileOption: string;
  emailOption: string;
  mobileLabel: string;
  emailLabel: string;
  passwordOtpLabel: string;
  loginViaOtp: string;
  usePassword: string;
  enterOtpPlaceholder: string;
  loginBtn: string;
  instantDemoTitle: string;
  continueDemoBtn: string;
  createAccountBtn: string;
  privacy: string;
  terms: string;
  forgotPassword: string;
  languageSelectLabel: string;
}

export interface LocalizedSeniorView {
  goodMorningGreeting: string;
  howAreYouFeeling: string;
  monitoringComfortDesc: string;
  morningCheckinTitle: string;
  checkinCompletedBadge: string;
  checkinDueBadge: string;
  nextCheckinTime: string;
  imOkSubtitle: string;
  needHelpSubtitle: string;
  talkToAranSubtitle: string;
  sosSubtitle: string;
  bpTargetNote: string;
  drinkOneGlassBtn: string;
  waterLoggedToast: string;
  checkinSuccessToast: string;
  heatWarningTitle: string;
  heatWarningBanner: string;
  heatWarningAction: string;
  ambulance108DispatchedTitle: string;
  ambulance108DispatchedDesc: string;
  whatDoYouNeedTitle: string;
  whatDoYouNeedSubtitle: string;
  callDaughterBtn: string;
  callDaughterSub: string;
  waterSub: string;
  foodSub: string;
  medicineSub: string;
  ambulance108Sub: string;
  primaryTreatingCareTeam: string;
  treatmentForDesc: string;
  viewFullMedicalReportBtn: string;
  doctorReportBtn: string;
}

export interface LocalizedDataBundle {
  medicalReport: LocalizedMedicalReport;
  medications: LocalizedMedication[];
  foodTimings: LocalizedFoodTiming[];
  familyMembers: LocalizedFamilyMember[];
  neighborhoodEmergencies: LocalizedNeighborhoodEmergency[];
  loginPage: LocalizedLoginPage;
  seniorView: LocalizedSeniorView;
}

export const localizedData: Record<Language, LocalizedDataBundle> = {
  en: {
    medicalReport: {
      primaryIllness: [
        'Hypertension (Stage 1 Essential, under pharmacological management)',
        'Mild Bilateral Knee Osteoarthritis (Degenerative joint disease)',
        'Type 2 Diabetes Mellitus (HbA1c: 6.7%, diet & medication stabilized)',
      ],
      ongoingTreatments: [
        'Telmisartan 40mg tablet daily morning after breakfast for cardiovascular stability',
        'Metformin 500mg SR tablet once daily after dinner for blood glucose regulation',
        'Glucosamine Sulfate 500mg + Calcium Carbonate & Vitamin D3 for joint cartilage support',
        'Prescribed 20-minute daily assisted indoor walking and low-sodium DASH dietary regimen',
      ],
      hospitalName: 'Apollo Hospitals, Greams Road, Chennai',
      hospitalAddress: '21 Greams Lane, Thousand Lights, Chennai, Tamil Nadu 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'Dr. Sundaram Ramanathan, MD, DM',
      doctorSpecialty: 'Senior Consultant Cardiologist & Geriatric Medicine Specialist',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (Cardiology Consultation & Renal Function Test)',
      bloodGroup: 'O Positive (O+)',
      allergies: ['Penicillin group (causes mild skin rash)', 'Sulfa antibiotics'],
      insuranceProvider: 'Star Health Senior Citizen Red Carpet Health Insurance',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (Cashless Hospitalization Desk)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'Telmisartan 40mg',
        dosage: '1 Tablet',
        time: '08:30 AM',
        instructions: 'After breakfast · Blood pressure regulation',
        category: 'Cardiovascular',
      },
      {
        id: 'MED-2',
        name: 'Calcium Carbonate + Vit D3 (500mg)',
        dosage: '1 Tablet',
        time: '01:00 PM',
        instructions: 'After lunch · Bone and cartilage strength',
        category: 'Supplements',
      },
      {
        id: 'MED-3',
        name: 'Metformin 500mg SR',
        dosage: '1 Tablet',
        time: '08:30 PM',
        instructions: 'After dinner · Blood sugar management',
        category: 'Endocrine',
      },
      {
        id: 'MED-4',
        name: 'Glucosamine Sulfate 500mg',
        dosage: '1 Capsule',
        time: '08:30 PM',
        instructions: 'After dinner · Knee joint flexibility',
        category: 'Joint Care',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'Morning Breakfast',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 Idlis, vegetable sambar with low salt, warm water',
        notes: 'Take Telmisartan 40mg 20 mins post-breakfast',
      },
      {
        id: 'FOOD-2',
        mealName: 'Nutritious Lunch',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'Brown rice, bottle gourd kootu, rasam, freshly set curd',
        notes: 'Low salt, rich in dietary fiber and potassium',
      },
      {
        id: 'FOOD-3',
        mealName: 'Evening Snacks & Tea',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'Boiled sundal (chickpeas) with ginger-cardamom warm herbal tea',
        notes: 'Hydration booster; 1 glass water mandatory',
      },
      {
        id: 'FOOD-4',
        mealName: 'Light Dinner',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 Soft wheat phulkas / chapathis with yellow moong dal & cucumber salad',
        notes: 'Followed by Metformin & Glucosamine tablets',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'Kavitha Ramaswamy',
        relationship: 'Daughter (Primary Caregiver)',
        phone: '+91 98401 23456',
        address: '14, 4th Seaward Road, Thiruvanmiyur, Chennai (3.2 km away)',
        notes: 'Visits every evening at 06:30 PM. Handles daily medication and grocery logistics.',
      },
      {
        id: 'FM-2',
        name: 'Vignesh Ramaswamy',
        relationship: 'Son (Secondary Caregiver)',
        phone: '+91 98840 87654',
        address: 'B-402, Green Meadows, Velachery, Chennai (6.8 km away)',
        notes: 'Available for weekend hospital appointments and emergency escalation.',
      },
      {
        id: 'FM-3',
        name: 'Rajesh Kannan',
        relationship: 'Son-in-law',
        phone: '+91 97900 11223',
        address: '14, 4th Seaward Road, Thiruvanmiyur, Chennai',
        notes: 'Coordinates vehicle logistics and hospital transport when required.',
      },
      {
        id: 'FM-4',
        name: 'Ananya Rajesh',
        relationship: 'Granddaughter',
        phone: '+91 98400 99881',
        address: 'Thiruvanmiyur, Chennai',
        notes: 'Speaks with grandmother every afternoon via ARAN audio/video companion.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 Tamil Nadu State Emergency Ambulance (GVK-EMRI)',
        type: 'Ambulance',
        phone: '108',
        distance: '1.2 km (Adyar Depot Station)',
        address: 'Near Adyar Depot, Lattice Bridge Road, Chennai',
      },
      {
        id: 'NE-2',
        name: 'Fortis Malar Hospital 24/7 Emergency Casualty',
        type: 'Hospital',
        phone: '044 4289 2222',
        distance: '900 meters (2.5 mins drive)',
        address: '52, 1st Main Rd, Gandhi Nagar, Adyar, Chennai 600020',
      },
      {
        id: 'NE-3',
        name: 'Adyar Police Station J-2 (Control Room)',
        type: 'Police',
        phone: '044 2491 0352 / 112',
        distance: '1.4 km',
        address: 'Sardar Patel Road, Adyar, Chennai 600020',
      },
      {
        id: 'NE-4',
        name: 'Mr. S. Kumar (Trusted Next-Door Neighbor)',
        type: 'Neighborhood Volunteer',
        phone: '+91 98403 11220',
        distance: '20 meters (Flat 2B, same floor)',
        address: 'Apartment 2B, Lakshmi Niwas, 2nd Main Rd, Adyar',
      },
    ],
    loginPage: {
      whoAreYou: 'Who Are You? (Select Role)',
      seniorPatient: 'Senior / Patient',
      familyCaregiver: 'Family / Caregiver',
      homeInCharge: 'Home In-Charge / Admin',
      seniorLivingArrangement: 'Senior Living Arrangement',
      careContext: 'Care Context',
      withFamily: {
        title: 'WITH FAMILY',
        subtitle: '👨‍👩‍👧 Lives with children',
        desc: 'Senior lives in shared home with sons, daughters or family members.',
      },
      livingIndependently: {
        title: 'LIVING INDEPENDENTLY',
        subtitle: '🏠 Lives alone independently',
        desc: 'Senior lives on their own; continuous remote sensor oversight enabled.',
      },
      withRelatives: {
        title: 'WITH RELATIVES',
        subtitle: '👥 Lives with relatives',
        desc: 'Senior resides with extended relatives, niece/nephew or siblings.',
      },
      withPartner: {
        title: 'WITH PARTNER',
        subtitle: '❤️ Lives with spouse',
        desc: 'Senior lives together with their elderly spouse or partner.',
      },
      authTitle: 'Authentication',
      mobileOption: 'Mobile Number',
      emailOption: 'Email',
      mobileLabel: 'Mobile Phone Number',
      emailLabel: 'Email Address',
      passwordOtpLabel: 'Password / OTP',
      loginViaOtp: 'Login via OTP',
      usePassword: 'Use Password',
      enterOtpPlaceholder: 'Enter 6-digit OTP',
      loginBtn: 'LOGIN TO ARAN CARE',
      instantDemoTitle: 'Instant Hackathon Demo',
      continueDemoBtn: 'CONTINUE AS DEMO (LAKSHMI & KAVITHA)',
      createAccountBtn: '+ Create New Senior Account & Onboarding',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      forgotPassword: 'Forgot Password',
      languageSelectLabel: 'Select App Language / மொழி:',
    },
    seniorView: {
      goodMorningGreeting: 'Good morning',
      howAreYouFeeling: 'How are you feeling right now?',
      monitoringComfortDesc: 'ARAN is monitoring your comfort, BP rate, water intake, and daily care schedule.',
      morningCheckinTitle: 'Morning Check-In',
      checkinCompletedBadge: '✓ Completed for today at 08:04 AM',
      checkinDueBadge: 'Due Now (Grace period active)',
      nextCheckinTime: 'Next Check-in: 06:00 PM (Evening)',
      imOkSubtitle: 'Confirm scheduled morning check-in',
      needHelpSubtitle: 'Water, meals, medication, or family assistance',
      talkToAranSubtitle: 'Tamil, Tanglish & English Voice Companion',
      sosSubtitle: 'Emergency 112, 108 Ambulance & family alert',
      bpTargetNote: 'Dr. Sundaram target: <130/85',
      drinkOneGlassBtn: '+ Drink 1 Glass (250ml)',
      waterLoggedToast: '1 Glass of water (+250ml) logged successfully.',
      checkinSuccessToast: 'Thank you Lakshmi Amma! Your check-in has been recorded.',
      heatWarningTitle: 'Room Heat Warning',
      heatWarningBanner: 'Room temperature is warm. Please switch on cooling fan and drink water.',
      heatWarningAction: 'Drink Water',
      ambulance108DispatchedTitle: '108 AMBULANCE DISPATCHED',
      ambulance108DispatchedDesc: 'En route to your Adyar home. Estimated arrival: 6 minutes.',
      whatDoYouNeedTitle: 'What do you need right now?',
      whatDoYouNeedSubtitle: 'Tap any button below. ARAN will record it and alert your caregiver immediately.',
      callDaughterBtn: 'Call Kavitha',
      callDaughterSub: 'Call Daughter',
      waterSub: 'Drink Water',
      foodSub: 'Food Need',
      medicineSub: 'Tablets',
      ambulance108Sub: 'Ambulance 108',
      primaryTreatingCareTeam: 'Primary Treating Care Team',
      treatmentForDesc: 'Treatment for: Hypertension, Osteoarthritis & Diabetes Management',
      viewFullMedicalReportBtn: 'View Full Medical Report',
      doctorReportBtn: 'Doctor Report',
    },
  },

  ta: {
    medicalReport: {
      primaryIllness: [
        'உயர் இரத்த அழுத்தம் (Stage 1 Essential Hypertension - தொடர் மருந்து உட்கொள்ளல்)',
        'இரு முழங்கால் மூட்டு தேய்மானம் (Mild Bilateral Knee Osteoarthritis)',
        'வகை 2 நீரிழிவு நோய் (Type 2 Diabetes Mellitus - HbA1c: 6.7%)',
      ],
      ongoingTreatments: [
        'டெல்மிசார்டன் 40mg மாத்திரை - தினமும் காலை உணவுக்குப் பின் இரத்த அழுத்தத்தைக் கட்டுப்படுத்த',
        'மெட்ஃபோர்மின் 500mg SR மாத்திரை - தினமும் இரவு உணவுக்குப் பின் சர்க்கரை அளவைக் கட்டுப்படுத்த',
        'குளூக்கோசமைன் சல்பேட் 500mg + கால்சியம் D3 - முழங்கால் மூட்டு வலி நிவாரணம் மற்றும் எலும்பு வலிமைக்கு',
        'மருத்துவர் பரிந்துரைத்த 20 நிமிட காலை நடைப்பயிற்சி மற்றும் குறைந்த உப்பு கொண்ட உணவு முறை',
      ],
      hospitalName: 'அப்பல்லோ மருத்துவமனை, கிரீம்ஸ் ரோடு, சென்னை',
      hospitalAddress: '21 கிரீம்ஸ் லேன், ஆயிரம் விளக்கு, சென்னை, தமிழ்நாடு 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'மருத்துவர் கே. சுந்தரம் ராமநாதன், MD, DM',
      doctorSpecialty: 'முதுநிலை இருதய நோய் மற்றும் முதியோர் நல சிறப்பு மருத்துவர்',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (இருதய பரிசோதனை & சிறுநீரக நல பரிசோதனை)',
      bloodGroup: 'O பாசிட்டிவ் (O+)',
      allergies: ['பென்சிலின் வகை மருந்துகள் (தோல் அரிப்பு ஏற்படும்)', 'சல்ஃபா ஆன்டிபயாடிக்ஸ்'],
      insuranceProvider: 'ஸ்டார் ஹெல்த் சீனியர் சிட்டிசன் ரெட் கார்பெட் மருத்துவ காப்பீடு',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (பணமில்லா மருத்துவ உதவி மையம்)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'டெல்மிசார்டன் 40mg (Telmisartan)',
        dosage: '1 மாத்திரை',
        time: '08:30 AM',
        instructions: 'காலை உணவுக்குப் பின் · இரத்த அழுத்தக் கட்டுப்பாடு',
        category: 'இருதய நலன்',
      },
      {
        id: 'MED-2',
        name: 'கால்சியம் கார்பனேட் + வைட்டமின் D3',
        dosage: '1 மாத்திரை',
        time: '01:00 PM',
        instructions: 'மதிய உணவுக்குப் பின் · மூட்டு மற்றும் எலும்பு வலிமை',
        category: 'சத்து மாத்திரை',
      },
      {
        id: 'MED-3',
        name: 'மெட்ஃபோர்மின் 500mg SR (Metformin)',
        dosage: '1 மாத்திரை',
        time: '08:30 PM',
        instructions: 'இரவு உணவுக்குப் பின் · இரத்த சர்க்கரை கட்டுப்பாடு',
        category: 'நீரிழிவு நலன்',
      },
      {
        id: 'MED-4',
        name: 'குளூக்கோசமைன் சல்பேட் 500mg',
        dosage: '1 காப்ஸ்யூல்',
        time: '08:30 PM',
        instructions: 'இரவு உணவுக்குப் பின் · முழங்கால் மூட்டு தேய்மான நிவாரணம்',
        category: 'மூட்டு நலன்',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'காலை சிற்றுண்டி (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 மென்மையான இட்லி, காய்கறி சாம்பார் (குறைந்த உப்பு), வெதுவெதுப்பான நீர்',
        notes: 'உணவுக்குப் பின் 20 நிமிடத்தில் டெல்மிசார்டன் 40mg மாத்திரை எடுக்கவும்',
      },
      {
        id: 'FOOD-2',
        mealName: 'மதிய உணவு (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'கைக்குத்தல் அரிசி சாதம், சுரைக்காய் கூட்டு, மிளகு ரசம், புதிய கெட்டித் தயிர்',
        notes: 'குறைந்த உப்பு, நார்ச்சத்து மற்றும் பொட்டாசியம் நிறைந்த சத்தான உணவு',
      },
      {
        id: 'FOOD-3',
        mealName: 'மாலை சிற்றுண்டி (Snacks)',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'வேகவைத்த கொண்டைக்கடலை சுண்டல், சுக்கு மல்லி மூலிகை தேநீர்',
        notes: 'தாகம் தணிக்க 1 டம்ளர் வெதுவெதுப்பான குடிநீர் கட்டாயம் அருந்தவும்',
      },
      {
        id: 'FOOD-4',
        mealName: 'இரவு உணவு (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 மென்மையான கோதுமை சப்பாத்தி, பாசிப்பருப்பு கூட்டு, வெள்ளரிக்காய் சாலட்',
        notes: 'இரவு உணவுக்குப் பின் மெட்ஃபோர்மின் & குளூக்கோசமைன் மாத்திரை எடுக்கவும்',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'கவிதா ராமசுவாமி',
        relationship: 'மூத்த மகள் (முதன்மை பராமரிப்பாளர்)',
        phone: '+91 98401 23456',
        address: '14, 4வது சீவார்டு ரோடு, திருவான்மியூர், சென்னை (3.2 கி.மீ தூரம்)',
        notes: 'தினமும் மாலை 06:30 மணிக்கு நேரில் வந்து சந்திக்கிறார். மருந்துகள் மற்றும் மளிகைப் பொருட்களைப் பராமரிக்கிறார்.',
      },
      {
        id: 'FM-2',
        name: 'விக்னேஷ் ராமசுவாமி',
        relationship: 'இளைய மகன் (இரண்டாம் நிலை பராமரிப்பாளர்)',
        phone: '+91 98840 87654',
        address: 'B-402, கிரீன் மெடோஸ், வேளச்சேரி, சென்னை (6.8 கி.மீ தூரம்)',
        notes: 'வார இறுதி மருத்துவமனை வருகை மற்றும் அவசர உதவிகளுக்கு உடனடியாக வரக்கூடியவர்.',
      },
      {
        id: 'FM-3',
        name: 'ராஜேஷ் கண்ணன்',
        relationship: 'மருமகன்',
        phone: '+91 97900 11223',
        address: '14, 4வது சீவார்டு ரோடு, திருவான்மியூர், சென்னை',
        notes: 'வாகன ஏற்பாடுகள் மற்றும் அவசர மருத்துவமனை போக்குவரத்துக்கு ஒருங்கிணைக்கிறார்.',
      },
      {
        id: 'FM-4',
        name: 'அனன்யா ராஜேஷ்',
        relationship: 'பேத்தி',
        phone: '+91 98400 99881',
        address: 'திருவான்மியூர், சென்னை',
        notes: 'தினமும் மதியம் பாட்டியுடன் அரண் சாதனத்தின் மூலம் அன்பாகப் பேசுகிறார்.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 தமிழ்நாடு அரசு அவசர ஆம்புலன்ஸ் சேவை (GVK-EMRI)',
        type: 'ஆம்புலன்ஸ்',
        phone: '108',
        distance: '1.2 கி.மீ (அடையாறு பணிமனை நிலையம்)',
        address: 'அடையாறு டிப்போ அருகில், எல்.பி. ரோடு, சென்னை',
      },
      {
        id: 'NE-2',
        name: 'ஃபோர்டிஸ் மலர் மருத்துவமனை 24/7 அவசர சிகிச்சை பிரிவு',
        type: 'மருத்துவமனை',
        phone: '044 4289 2222',
        distance: '900 மீட்டர் (2.5 நிமிட பயண தூரம்)',
        address: '52, 1வது பிரதான சாலை, காந்தி நகர், அடையாறு, சென்னை 600020',
      },
      {
        id: 'NE-3',
        name: 'அடையாறு காவல் நிலையம் J-2 (கட்டுப்பாட்டு அறை)',
        type: 'காவல் நிலையம்',
        phone: '044 2491 0352 / 112',
        distance: '1.4 கி.மீ',
        address: 'சர்தார் படேல் சாலை, அடையாறு, சென்னை 600020',
      },
      {
        id: 'NE-4',
        name: 'திரு. எஸ். குமார் (நம்பகமான அண்டை வீட்டார்)',
        type: 'அண்டை வீட்டு தொண்டர்',
        phone: '+91 98403 11220',
        distance: '20 மீட்டர் (அடுக்குமாடி குடியிருப்பு 2B, அதே தளம்)',
        address: 'பிளாட் 2B, லட்சுமி நிவாஸ், 2வது பிரதான சாலை, அடையாறு',
      },
    ],
    loginPage: {
      whoAreYou: 'நீங்கள் யார்? (பங்கு தேர்ந்தெடுக்கவும்)',
      seniorPatient: 'முதியவர் / நோயாளி',
      familyCaregiver: 'குடும்பம் / பராமரிப்பாளர்',
      homeInCharge: 'இல்லப் பொறுப்பாளர் / நிர்வாகி',
      seniorLivingArrangement: 'முதியவர் வசிப்பிட வகை',
      careContext: 'பராமரிப்பு சூழல்',
      withFamily: {
        title: 'குடும்பத்துடன்',
        subtitle: '👨‍👩‍👧 பிள்ளைகளுடன் வசிப்பவர்',
        desc: 'முதியவர் தனது மகன், மகள் அல்லது குடும்ப உறுப்பினர்களுடன் ஒன்றாக வசிக்கிறார்.',
      },
      livingIndependently: {
        title: 'தனித்து வசிப்பவர்',
        subtitle: '🏠 தனியாக சுயமாக வசிப்பவர்',
        desc: 'முதியவர் தனியாக வசிக்கிறார்; அரண் சாதனத்தின் 24 மணி நேர தானியங்கி கண்காணிப்பு செயல்படும்.',
      },
      withRelatives: {
        title: 'உறவினர்களுடன்',
        subtitle: '👥 உறவினர்களுடன் வசிப்பவர்',
        desc: 'முதியவர் அக்கா, தம்பி, மருமகள் போன்ற உறவினர்களின் வீட்டில் வசிக்கிறார்.',
      },
      withPartner: {
        title: 'துணையுடன்',
        subtitle: '❤️ வாழ்க்கை துணையுடன் வசிப்பவர்',
        desc: 'முதியவர் தனது வயதான கணவர்/மனைவியுடன் இணைந்து வசிக்கிறார்.',
      },
      authTitle: 'உள்நுழைவு அங்கீகாரம்',
      mobileOption: 'கைபேசி எண்',
      emailOption: 'மின்னஞ்சல்',
      mobileLabel: 'கைபேசி எண்',
      emailLabel: 'மின்னஞ்சல் முகவரி',
      passwordOtpLabel: 'கடவுச்சொல் / ஒருமுறை கடவுச்சொல் (OTP)',
      loginViaOtp: 'OTP மூலம் உள்நுழைக',
      usePassword: 'கடவுச்சொல்லைப் பயன்படுத்துக',
      enterOtpPlaceholder: '6 இலக்க OTP எண்ணை உள்ளிடவும்',
      loginBtn: 'அரண் பராமரிப்பில் உள்நுழைக',
      instantDemoTitle: 'நேரடி மாதிரி செயல்விளக்கம் (Demo)',
      continueDemoBtn: 'மாதிரியாக தொடரவும் (லட்சுமி & கவிதா)',
      createAccountBtn: '+ புதிய முதியவர் கணக்கு மற்றும் அமைப்புகள்',
      privacy: 'தனியுரிமை கொள்கை',
      terms: 'சேவை விதிமுறைகள்',
      forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
      languageSelectLabel: 'பயன்பாட்டு மொழி / Select Language:',
    },
    seniorView: {
      goodMorningGreeting: 'காலை வணக்கம்',
      howAreYouFeeling: 'நீங்கள் இப்போது சௌக்கியமாக இருக்கிறீர்களா?',
      monitoringComfortDesc: 'உங்கள் நலம், இரத்த அழுத்தம் (BP), தண்ணீர் அளவு மற்றும் மாத்திரை நேரங்களை அரண் கண்காணித்து வருகிறது.',
      morningCheckinTitle: 'காலை செக்-இன் (Morning Check-In)',
      checkinCompletedBadge: '✓ இன்று காலை 08:04 மணிக்கு உறுதி செய்யப்பட்டது',
      checkinDueBadge: 'இப்போது செக்-இன் நேரம் வந்துவிட்டது',
      nextCheckinTime: 'அடுத்த செக்-இன்: மாலை 06:00 மணி',
      imOkSubtitle: 'காலை செக்-இன்னை உறுதி செய்கிறேன் · நலம்',
      needHelpSubtitle: 'தண்ணீர், உணவு, மருந்து அல்லது பராமரிப்பாளர் உதவி',
      talkToAranSubtitle: 'அரணிடம் தமிழில் குரல் மூலம் பேசவும்',
      sosSubtitle: '112 அவசர உதவி, 108 ஆம்புலன்ஸ் மற்றும் குடும்ப எச்சரிக்கை',
      bpTargetNote: 'மருத்துவர் சுந்தரம் பரிந்துரைத்த அளவு: <130/85',
      drinkOneGlassBtn: '+ 1 டம்ளர் தண்ணீர் குடித்தேன் (250ml)',
      waterLoggedToast: '1 டம்ளர் தண்ணீர் (+250 மிலி) அருந்தியது பதிவு செய்யப்பட்டது.',
      checkinSuccessToast: 'மகிழ்ச்சி லட்சுமி அம்மா! உங்கள் காலை செக்-இன் பதிவு செய்யப்பட்டது.',
      heatWarningTitle: 'அறை வெப்ப எச்சரிக்கை',
      heatWarningBanner: 'அறை மிகவும் சூடாக உள்ளது. தயவுசெய்து மின்விசிறியை இயக்கி தண்ணீர் குடியுங்கள்.',
      heatWarningAction: 'தண்ணீர் குடிக்கவும்',
      ambulance108DispatchedTitle: '108 ஆம்புலன்ஸ் வரவழைக்கப்பட்டது',
      ambulance108DispatchedDesc: 'உங்கள் அடையாறு வீட்டிற்கு விரைந்து வருகிறது. வருகை நேரம்: 6 நிமிடங்கள்.',
      whatDoYouNeedTitle: 'உங்களுக்கு இப்போது என்ன உதவி வேண்டும்?',
      whatDoYouNeedSubtitle: 'கீழே உள்ள ஏதேனும் ஒரு பொத்தானைத் தொடவும். அரண் உடனடியாக பதிவு செய்து மகளுக்குத் தெரிவிக்கும்.',
      callDaughterBtn: 'கவிதாவை அழைக்க',
      callDaughterSub: 'மகளிடம் பேச',
      waterSub: 'தண்ணீர் தேவை',
      foodSub: 'உணவு உதவி',
      medicineSub: 'மாத்திரை',
      ambulance108Sub: '108 ஆம்புலன்ஸ்',
      primaryTreatingCareTeam: 'முதன்மை சிகிச்சை மருத்துவக் குழு',
      treatmentForDesc: 'சிகிச்சை: உயர் இரத்த அழுத்தம், முழங்கால் தேய்மானம் மற்றும் நீரிழிவு மேலாண்மை',
      viewFullMedicalReportBtn: 'முழு மருத்துவ அறிக்கையைக் காண்க',
      doctorReportBtn: 'மருத்துவ அறிக்கை',
    },
  },

  hi: {
    medicalReport: {
      primaryIllness: [
        'उच्च रक्तचाप (Stage 1 Essential Hypertension - नियमित दवा प्रबंधन)',
        'घुटने का ऑस्टियोआर्थराइटिस (Mild Bilateral Knee Osteoarthritis)',
        'टाइप 2 मधुमेह (Type 2 Diabetes Mellitus - HbA1c: 6.7%)',
      ],
      ongoingTreatments: [
        'टेल्मीसार्टन 40mg गोली - रक्तचाप स्थिरता के लिए प्रतिदिन सुबह नाश्ते के बाद',
        'मेटफॉर्मिन 500mg SR गोली - रक्त शर्करा नियंत्रण हेतु रात के खाने के बाद',
        'ग्लुकोसामाइन सल्फेट 500mg + कैल्शियम D3 - घुटने के जोड़ों और हड्डियों की मजबूती के लिए',
        'प्रतिदिन 20 मिनट सुबह की सैर और कम नमक वाला विशेष आहार',
      ],
      hospitalName: 'अपोलो हॉस्पिटल्स, ग्रीम्स रोड, चेन्नई',
      hospitalAddress: '21 ग्रीम्स लेन, थाउजेंड लाइट्स, चेन्नई, तमिलनाडु 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'डॉ. सुंदरम रामनाथन, MD, DM',
      doctorSpecialty: 'वरिष्ठ हृदय रोग व वृद्धावस्था चिकित्सा विशेषज्ञ',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (कार्डियोलॉजी व रीनल फंक्शन जांच)',
      bloodGroup: 'ओ पॉजिटिव (O+)',
      allergies: ['पेनिसिलिन वर्ग की दवाएं (त्वचा पर चकत्ते)', 'सल्फा एंटीबायोटिक्स'],
      insuranceProvider: 'स्टार हेल्थ सीनियर सिटीजन रेड कार्पेट स्वास्थ्य बीमा',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (कैशलेस अस्पताल सेवा डेस्क)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'टेल्मीसार्टन 40mg (Telmisartan)',
        dosage: '1 गोली',
        time: '08:30 AM',
        instructions: 'सुबह नाश्ते के बाद · रक्तचाप नियंत्रण',
        category: 'हृदय स्वास्थ्य',
      },
      {
        id: 'MED-2',
        name: 'कैल्शियम कार्बोनेट + विटामिन D3 (500mg)',
        dosage: '1 गोली',
        time: '01:00 PM',
        instructions: 'दोपहर भोजन के बाद · हड्डियों की मजबूती',
        category: 'सप्लीमेंट्स',
      },
      {
        id: 'MED-3',
        name: 'मेटफॉर्मिन 500mg SR (Metformin)',
        dosage: '1 गोली',
        time: '08:30 PM',
        instructions: 'रात के भोजन के बाद · ब्लड शुगर नियंत्रण',
        category: 'मधुमेह',
      },
      {
        id: 'MED-4',
        name: 'ग्लुकोसामाइन सल्फेट 500mg',
        dosage: '1 कैप्सूल',
        time: '08:30 PM',
        instructions: 'रात के भोजन के बाद · जोड़ों के दर्द से राहत',
        category: 'जोड़ों का स्वास्थ्य',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'सुबह का नाश्ता (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 इडली, कम नमक वाली सांभर, गुनगुना पानी',
        notes: 'नाश्ते के 20 मिनट बाद टेल्मीसार्टन 40mg गोली लें',
      },
      {
        id: 'FOOD-2',
        mealName: 'दोपहर का भोजन (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'ब्राउन राइस, लौकी की सब्जी, दाल/रसम, ताजा दही',
        notes: 'कम नमक, फाइबर और पोटेशियम से भरपूर आहार',
      },
      {
        id: 'FOOD-3',
        mealName: 'शाम का नाश्ता (Snacks)',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'उबले हुए चने (सुंडल) व अदरक-इलायची की हर्बल चाय',
        notes: 'हाइड्रेशन के लिए 1 गिलास पानी जरूर पिएं',
      },
      {
        id: 'FOOD-4',
        mealName: 'रात का भोजन (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 नरम गेहूं की रोटियां, मूंग दाल व खीरा सलाद',
        notes: 'भोजन के बाद मेटफॉर्मिन और ग्लुकोसामाइन दवा लें',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'कविता रामस्वामी',
        relationship: 'बड़ी बेटी (प्राथमिक देखभालकर्ता)',
        phone: '+91 98401 23456',
        address: '14, 4थ सीवार्ड रोड, तिरुवान्मियूर, चेन्नई (3.2 किमी दूर)',
        notes: 'प्रतिदिन शाम 6:30 बजे आती हैं। दवाइयों और घर के सामान का प्रबंधन करती हैं।',
      },
      {
        id: 'FM-2',
        name: 'विग्नेश रामस्वामी',
        relationship: 'छोटा बेटा (द्वितीयक देखभालकर्ता)',
        phone: '+91 98840 87654',
        address: 'बी-402, ग्रीन मीडोज, वेलाचेरी, चेन्नई (6.8 किमी दूर)',
        notes: 'सप्ताहांत पर अस्पताल व आपातकालीन सहायता के लिए उपलब्ध।',
      },
      {
        id: 'FM-3',
        name: 'राजेश कन्नन',
        relationship: 'दामाद',
        phone: '+91 97900 11223',
        address: 'तिरुवान्मियूर, चेन्नई',
        notes: 'वाहन व्यवस्था और आपातकालीन अस्पताल यात्रा में सहयोग करते हैं।',
      },
      {
        id: 'FM-4',
        name: 'अनन्या राजेश',
        relationship: 'पोती / नातिन',
        phone: '+91 98400 99881',
        address: 'तिरुवान्मियूर, चेन्नई',
        notes: 'प्रतिदिन दोपहर में अरण डिवाइस से दादी से बात करती हैं।',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 आपातकालीन एम्बुलेंस सेवा (GVK-EMRI)',
        type: 'एम्बुलेंस',
        phone: '108',
        distance: '1.2 किमी (अडयार स्टेशन)',
        address: 'अडयार डिपो के पास, एल.बी. रोड, चेन्नई',
      },
      {
        id: 'NE-2',
        name: 'फोर्टिस मलार अस्पताल 24/7 आपातकालीन विभाग',
        type: 'अस्पताल',
        phone: '044 4289 2222',
        distance: '900 मीटर (2.5 मिनट)',
        address: '52, 1स्ट मेन रोड, गांधी नगर, अडयार, चेन्नई 600020',
      },
      {
        id: 'NE-3',
        name: 'अडयार पुलिस थाना J-2',
        type: 'पुलिस',
        phone: '044 2491 0352 / 112',
        distance: '1.4 किमी',
        address: 'सरदार पटेल रोड, अडयार, चेन्नई',
      },
      {
        id: 'NE-4',
        name: 'श्री एस. कुमार (विश्वसनीय पड़ोसी)',
        type: 'पड़ोसी स्वयंसेवक',
        phone: '+91 98403 11220',
        distance: '20 मीटर (फ्लैट 2B, उसी मंजिल पर)',
        address: 'अपार्टमेंट 2B, लक्ष्मी निवास, अडयार',
      },
    ],
    loginPage: {
      whoAreYou: 'आप कौन हैं? (भूमिका चुनें)',
      seniorPatient: 'वरिष्ठ नागरिक / मरीज',
      familyCaregiver: 'परिवार / देखभालकर्ता',
      homeInCharge: 'गृह प्रभारी / व्यवस्थापक',
      seniorLivingArrangement: 'वरिष्ठ नागरिक आवास व्यवस्था',
      careContext: 'देखभाल संदर्भ',
      withFamily: {
        title: 'परिवार के साथ',
        subtitle: '👨‍👩‍👧 बच्चों व परिवार के साथ',
        desc: 'वरिष्ठ नागरिक अपने बेटे, बेटी या परिवार के सदस्यों के साथ रहते हैं।',
      },
      livingIndependently: {
        title: 'स्वतंत्र रूप से',
        subtitle: '🏠 अकेले स्वतंत्र रहते हैं',
        desc: 'वरिष्ठ नागरिक अकेले रहते हैं; अरण द्वारा 24 घंटे दूरस्थ निगरानी सक्रिय रहती है।',
      },
      withRelatives: {
        title: 'रिश्तेदारों के साथ',
        subtitle: '👥 रिश्तेदारों के साथ रहते हैं',
        desc: 'वरिष्ठ नागरिक अपने भाई-बहन या अन्य रिश्तेदारों के घर रहते हैं।',
      },
      withPartner: {
        title: 'जीवनसाथी के साथ',
        subtitle: '❤️ जीवनसाथी के साथ रहते हैं',
        desc: 'वरिष्ठ नागरिक अपने वृद्ध पति/पत्नी के साथ रहते हैं।',
      },
      authTitle: 'प्रमाणीकरण (Login)',
      mobileOption: 'मोबाइल नंबर',
      emailOption: 'ईमेल',
      mobileLabel: 'मोबाइल फोन नंबर',
      emailLabel: 'ईमेल पता',
      passwordOtpLabel: 'पासवर्ड / ओटीपी',
      loginViaOtp: 'OTP द्वारा लॉगिन करें',
      usePassword: 'पासवर्ड का उपयोग करें',
      enterOtpPlaceholder: '6 अंकों का OTP दर्ज करें',
      loginBtn: 'अरण केयर में लॉगिन करें',
      instantDemoTitle: 'तत्काल लाइव डेमो',
      continueDemoBtn: 'डेमो जारी रखें (लक्ष्मी व कविता)',
      createAccountBtn: '+ नया खाता बनाएं व सेटअप करें',
      privacy: 'गोपनीयता नीति',
      terms: 'सेवा की शर्तें',
      forgotPassword: 'पासवर्ड भूल गए?',
      languageSelectLabel: 'ऐप भाषा चुनें / Select Language:',
    },
    seniorView: {
      goodMorningGreeting: 'शुभ प्रभात',
      howAreYouFeeling: 'आप अभी कैसा महसूस कर रहे हैं?',
      monitoringComfortDesc: 'अरण आपके स्वास्थ्य, बीपी, पानी व दवाइयों की निरंतर देखरेख कर रहा है।',
      morningCheckinTitle: 'सुबह का चेक-इन',
      checkinCompletedBadge: '✓ आज सुबह 08:04 बजे संपन्न हुआ',
      checkinDueBadge: 'चेक-इन का समय हो गया है',
      nextCheckinTime: 'अगला चेक-इन: शाम 06:00 बजे',
      imOkSubtitle: 'मैं ठीक हूँ · चेक-इन की पुष्टि',
      needHelpSubtitle: 'पानी, भोजन, दवा या परिवार की मदद',
      talkToAranSubtitle: 'अरण से अपनी भाषा में बात करें',
      sosSubtitle: '112 आपातकाल, 108 एम्बुलेंस व परिवार को अलर्ट',
      bpTargetNote: 'डॉ. सुंदरम लक्ष्य: <130/85',
      drinkOneGlassBtn: '+ 1 गिलास पानी पिया (250ml)',
      waterLoggedToast: '1 गिलास पानी (+250ml) दर्ज किया गया।',
      checkinSuccessToast: 'धन्यवाद लक्ष्मी जी! आपका चेक-इन दर्ज हो गया है।',
      heatWarningTitle: 'कमरे की गर्मी चेतावनी',
      heatWarningBanner: 'कमरे का तापमान अधिक है। कृपया पंखा चलाएं और पानी पिएं।',
      heatWarningAction: 'पानी पिएं',
      ambulance108DispatchedTitle: '108 एम्बुलेंस रवाना हो चुकी है',
      ambulance108DispatchedDesc: 'आपके घर के रास्ते में है। अनुमानित समय: 6 मिनट।',
      whatDoYouNeedTitle: 'आपको अभी क्या सहायता चाहिए?',
      whatDoYouNeedSubtitle: 'नीचे किसी भी बटन को दबाएं। अरण तुरंत आपकी बेटी को सूचित करेगा।',
      callDaughterBtn: 'कविता को कॉल करें',
      callDaughterSub: 'बेटी से बात करें',
      waterSub: 'पानी चाहिए',
      foodSub: 'भोजन चाहिए',
      medicineSub: 'दवाई चाहिए',
      ambulance108Sub: '108 एम्बुलेंस',
      primaryTreatingCareTeam: 'प्राथमिक उपचार विशेषज्ञ टीम',
      treatmentForDesc: 'उपचार: उच्च रक्तचाप, घुटने का दर्द व मधुमेह नियंत्रण',
      viewFullMedicalReportBtn: 'पूरी स्वास्थ्य रिपोर्ट देखें',
      doctorReportBtn: 'डॉक्टर रिपोर्ट',
    },
  },

  ml: {
    medicalReport: {
      primaryIllness: [
        'ഉയർന്ന രക്തസമ്മർദ്ദം (Stage 1 Essential Hypertension)',
        'മുട്ട് തേയ്മാനം (Mild Bilateral Knee Osteoarthritis)',
        'ടൈപ്പ് 2 പ്രമേഹം (Type 2 Diabetes Mellitus - HbA1c: 6.7%)',
      ],
      ongoingTreatments: [
        'ടെൽമിസാർട്ടൻ 40mg ഗുളിക - രാവിലെ ഭക്ഷണത്തിന് ശേഷം ബിപി നിയന്ത്രണത്തിന്',
        'മെറ്റ്ഫോർമിൻ 500mg SR ഗുളിക - രാത്രി ഭക്ഷണത്തിന് ശേഷം ഷുഗർ നിയന്ത്രണത്തിന്',
        'ഗ്ലൂക്കോസാമൈൻ 500mg + കാൽസ്യം D3 - സന്ധി വേദന ശമനത്തിനും അസ്ഥി ബലത്തിനും',
        'ദിവസേന 20 മിനിറ്റ് നടത്തവും ഉപ്പ് കുറച്ച പ്രത്യേക ഭക്ഷണക്രമവും',
      ],
      hospitalName: 'അപ്പോളോ ഹോസ്പിറ്റൽസ്, ഗ്രീംസ് റോഡ്, ചെന്നൈ',
      hospitalAddress: '21 ഗ്രീംസ് ലെയ്ൻ, തൗസൻഡ് ലൈറ്റ്സ്, ചെന്നൈ 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'ഡോ. സുന്ദരം രാമനാഥൻ, MD, DM',
      doctorSpecialty: 'സീനിയർ കൺസൾട്ടന്റ് കാർഡിയോളജിസ്റ്റ് & ജെറിയാട്രിക് സ്പെഷ്യലിസ്റ്റ്',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (ഹൃദയ പരിശോധന & കിഡ്നി ഫംഗ്ഷൻ ടെസ്റ്റ്)',
      bloodGroup: 'ഒ പോസിറ്റീവ് (O+)',
      allergies: ['പെൻസിലിൻ അലർജി', 'സൾഫ മരുന്നുകൾ'],
      insuranceProvider: 'സ്റ്റാർ ഹെൽത്ത് സീനിയർ സിറ്റിസൺ റെഡ് കാർപെറ്റ് ഇൻഷുറൻസ്',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (ക്യാഷ്‌ലെസ്സ് ആശുപത്രി ഡെസ്ക്)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'ടെൽമിസാർട്ടൻ 40mg',
        dosage: '1 ഗുളിക',
        time: '08:30 AM',
        instructions: 'രാവിലെ ഭക്ഷണത്തിന് ശേഷം · ബിപി നിയന്ത്രണം',
        category: 'ഹൃദയാരോഗ്യം',
      },
      {
        id: 'MED-2',
        name: 'കാൽസ്യം കാർബണേറ്റ് + വൈറ്റമിൻ D3',
        dosage: '1 ഗുളിക',
        time: '01:00 PM',
        instructions: 'ഉച്ചഭക്ഷണത്തിന് ശേഷം · അസ്ഥി ബലം',
        category: 'സപ്ലിമെന്റ്',
      },
      {
        id: 'MED-3',
        name: 'മെറ്റ്ഫോർമിൻ 500mg SR',
        dosage: '1 ഗുളിക',
        time: '08:30 PM',
        instructions: 'രാത്രി ഭക്ഷണത്തിന് ശേഷം · പ്രമേഹ നിയന്ത്രണം',
        category: 'പ്രമേഹം',
      },
      {
        id: 'MED-4',
        name: 'ഗ്ലൂക്കോസാമൈൻ 500mg',
        dosage: '1 ക്യാപ്സൂൾ',
        time: '08:30 PM',
        instructions: 'രാത്രി ഭക്ഷണത്തിന് ശേഷം · മുട്ടുവേദന ശമനം',
        category: 'സന്ധി പരിചരണം',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'പ്രഭാതഭക്ഷണം (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 ഇഡ്ഡലി, ഉപ്പ് കുറഞ്ഞ സാമ്പാർ, ചെറുചൂടുവെള്ളം',
        notes: 'ഭക്ഷണത്തിന് ശേഷം ടെൽമിസാർട്ടൻ 40mg ഗുളിക കഴിക്കുക',
      },
      {
        id: 'FOOD-2',
        mealName: 'ഉച്ചഭക്ഷണം (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'തവിട് കളയാത്ത ചോറ്, പച്ചക്കറി കറി, രസം, തൈര്',
        notes: 'ഉപ്പ് കുറഞ്ഞതും നാരുകൾ അടങ്ങിയതുമായ ഭക്ഷണം',
      },
      {
        id: 'FOOD-3',
        mealName: 'വൈകുന്നേരത്തെ ചായ (Snacks)',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'പുഴുങ്ങിയ കടല, ഇഞ്ചി തുളസി ചായ',
        notes: '1 ഗ്ലാസ് വെള്ളം നിർബന്ധമായും കുടിക്കുക',
      },
      {
        id: 'FOOD-4',
        mealName: 'അത്താഴം (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 ഗോതമ്പ് ചപ്പാത്തി, ചെറുപയർ പരിപ്പ് കറി, സാലഡ്',
        notes: 'ഭക്ഷണത്തിന് ശേഷം മെറ്റ്ഫോർമിൻ ഗുളിക കഴിക്കുക',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'കവിത രാമസ്വാമി',
        relationship: 'മൂത്ത മകൾ (പ്രധാന പരിചാരക)',
        phone: '+91 98401 23456',
        address: 'തിരുവാന്മിയൂർ, ചെന്നൈ (3.2 കി.മീ)',
        notes: 'എല്ലാ ദിവസവും വൈകുന്നേരം സന്ദർശിക്കുന്നു.',
      },
      {
        id: 'FM-2',
        name: 'വിഘ്നേഷ് രാമസ്വാമി',
        relationship: 'മകൻ (രണ്ടാം പരിചാരകൻ)',
        phone: '+91 98840 87654',
        address: 'വേളച്ചേരി, ചെന്നൈ',
        notes: 'അടിയന്തര ആവശ്യങ്ങൾക്ക് ലഭ്യമാണ്.',
      },
      {
        id: 'FM-3',
        name: 'രാജേഷ് കണ്ണൻ',
        relationship: 'മരുമകൻ',
        phone: '+91 97900 11223',
        address: 'ചെന്നൈ',
        notes: 'വാഹന സഹായം നൽകുന്നു.',
      },
      {
        id: 'FM-4',
        name: 'അനന്യ രാജേഷ്',
        relationship: 'പേരക്കുട്ടി',
        phone: '+91 98400 99881',
        address: 'ചെന്നൈ',
        notes: 'എല്ലാ ദിവസവും സംസാരിക്കുന്നു.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 എമർജൻസി ആംബുലൻസ് സർവീസ്',
        type: 'ആംബുലൻസ്',
        phone: '108',
        distance: '1.2 കി.മീ (അഡയാർ)',
        address: 'അഡയാർ ഡിപ്പോയ്ക്ക് സമീപം, ചെന്നൈ',
      },
      {
        id: 'NE-2',
        name: 'ഫോർട്ടിസ് മലർ ആശുപത്രി 24/7 എമർജൻസി',
        type: 'ആശുപത്രി',
        phone: '044 4289 2222',
        distance: '900 മീറ്റർ (2.5 മിനിറ്റ്)',
        address: 'ഗാന്ധി നഗർ, അഡയാർ, ചെന്നൈ',
      },
      {
        id: 'NE-3',
        name: 'അഡയാർ പോലീസ് സ്റ്റേഷൻ J-2',
        type: 'പോലീസ്',
        phone: '044 2491 0352 / 112',
        distance: '1.4 കി.മീ',
        address: 'സർദാർ പട്ടേൽ റോഡ്, അഡയാർ',
      },
      {
        id: 'NE-4',
        name: 'ശ്രീ എസ്. കുമാർ (അയൽവാസി)',
        type: 'അയൽപക്ക സന്നദ്ധപ്രവർത്തകൻ',
        phone: '+91 98403 11220',
        distance: '20 മീറ്റർ (ഫ്ലാറ്റ് 2B)',
        address: 'ലക്ഷ്മി നിവാസ്, അഡയാർ',
      },
    ],
    loginPage: {
      whoAreYou: 'ആരാണ് നിങ്ങൾ? (റോൾ തിരഞ്ഞെടുക്കുക)',
      seniorPatient: 'മുതിർന്നയാൾ / രോഗി',
      familyCaregiver: 'കുടുംബം / പരിചാരകൻ',
      homeInCharge: 'ഇൻ-ചാർജ്ജ് / അഡ്മിൻ',
      seniorLivingArrangement: 'താമസ സൗകര്യം',
      careContext: 'പരിചരണ പശ്ചാത്തലം',
      withFamily: {
        title: 'കുടുംബത്തോടൊപ്പം',
        subtitle: '👨‍👩‍👧 മക്കളോടൊപ്പം താമസിക്കുന്നു',
        desc: 'മുതിർന്നയാൾ മക്കളോടൊപ്പമോ കുടുംബത്തോടൊപ്പമോ താമസിക്കുന്നു.',
      },
      livingIndependently: {
        title: 'ഒറ്റയ്ക്ക് താമസിക്കുന്നയാൾ',
        subtitle: '🏠 ഒറ്റയ്ക്ക് സ്വതന്ത്രമായി ജീവിക്കുന്നു',
        desc: 'മുതിർന്നയാൾ ഒറ്റയ്ക്ക് താമസിക്കുന്നു; അരൺ തുടർച്ചയായി നിരീക്ഷിക്കുന്നു.',
      },
      withRelatives: {
        title: 'ബന്ധുക്കളോടൊപ്പം',
        subtitle: '👥 ബന്ധുക്കളോടൊപ്പം താമസിക്കുന്നു',
        desc: 'മുതിർന്നയാൾ ബന്ധുക്കളുടെ വീട്ടിൽ താമസിക്കുന്നു.',
      },
      withPartner: {
        title: 'പങ്കാളിയോടൊപ്പം',
        subtitle: '❤️ പങ്കാളിയോടൊപ്പം താമസിക്കുന്നു',
        desc: 'മുതിർന്നയാൾ വൃദ്ധനായ പങ്കാളിയോടൊപ്പം ജീവിക്കുന്നു.',
      },
      authTitle: 'ലോഗിൻ വിവരങ്ങൾ',
      mobileOption: 'മൊബൈൽ നമ്പർ',
      emailOption: 'ഇമെയിൽ',
      mobileLabel: 'മൊബൈൽ ഫോൺ നമ്പർ',
      emailLabel: 'ഇമെയിൽ വിലാസം',
      passwordOtpLabel: 'പാസ്‌വേഡ് / ഒടിപി',
      loginViaOtp: 'OTP വഴി ലോഗിൻ ചെയ്യുക',
      usePassword: 'പാസ്‌വേഡ് ഉപയോഗിക്കുക',
      enterOtpPlaceholder: '6 അക്ക OTP നൽകുക',
      loginBtn: 'അരൺ കെയറിൽ ലോഗിൻ ചെയ്യുക',
      instantDemoTitle: 'തത്സമയ ഡെമോ',
      continueDemoBtn: 'ഡെമോ തുടരുക (ലക്ഷ്മി & കവിത)',
      createAccountBtn: '+ പുതിയ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      privacy: 'സ്വകാര്യതാ നയം',
      terms: 'സേവന വ്യവസ്ഥകൾ',
      forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
      languageSelectLabel: 'ഭാഷ തിരഞ്ഞെടുക്കുക / Select Language:',
    },
    seniorView: {
      goodMorningGreeting: 'സുപ്രഭാതം',
      howAreYouFeeling: 'ഇപ്പോൾ എങ്ങനെയുണ്ട്? സുഖമാണോ?',
      monitoringComfortDesc: 'അരൺ നിങ്ങളുടെ ആരോഗ്യവും ബിപിയും മരുന്നും ഭക്ഷണവും ശ്രദ്ധിക്കുന്നു.',
      morningCheckinTitle: 'രാവിലെ ചെക്ക്-ഇൻ',
      checkinCompletedBadge: '✓ ഇന്ന് രാവിലെ 08:04 ന് പൂർത്തിയായി',
      checkinDueBadge: 'ചെക്ക്-ഇൻ സമയമായി',
      nextCheckinTime: 'അടുത്ത ചെക്ക്-ഇൻ: വൈകുന്നേരം 06:00 മണി',
      imOkSubtitle: 'സുഖമായിരിക്കുന്നു · ചെക്ക്-ഇൻ സ്ഥിരീകരണം',
      needHelpSubtitle: 'വെള്ളം, ഭക്ഷണം, മരുന്ന് അല്ലെങ്കിൽ കുടുംബ സഹായം',
      talkToAranSubtitle: 'അരണുമായി സംസാരിക്കുക',
      sosSubtitle: '112 എമർജൻസി, 108 ആംബുലൻസ് അലേർട്ട്',
      bpTargetNote: 'ഡോ. സുന്ദരം നിർദ്ദേശം: <130/85',
      drinkOneGlassBtn: '+ 1 ഗ്ലാസ് വെള്ളം കുടിച്ചു (250ml)',
      waterLoggedToast: '1 ഗ്ലാസ് വെള്ളം കുടിച്ചത് രേഖപ്പെടുത്തി.',
      checkinSuccessToast: 'നന്ദി ലക്ഷ്മി അമ്മ! ചെക്ക്-ഇൻ രേഖപ്പെടുത്തി.',
      heatWarningTitle: 'മുറിയിലെ ചൂട് മുന്നറിയിപ്പ്',
      heatWarningBanner: 'മുറിയിൽ ചൂട് കൂടുതലാണ്. ഫാൻ ഇടുക, വെള്ളം കുടിക്കുക.',
      heatWarningAction: 'വെള്ളം കുടിക്കുക',
      ambulance108DispatchedTitle: '108 ആംബുലൻസ് പുറപ്പെട്ടു',
      ambulance108DispatchedDesc: 'നിങ്ങളുടെ വീട്ടിലേക്ക് വരുന്നു. എത്തുന്ന സമയം: 6 മിനിറ്റ്.',
      whatDoYouNeedTitle: 'ഇപ്പോൾ എന്ത് സഹായമാണ് വേണ്ടത്?',
      whatDoYouNeedSubtitle: 'താഴെയുള്ള ബട്ടണിൽ തൊടുക. അരൺ ഉടൻ തന്നെ മകളെ അറിയിക്കും.',
      callDaughterBtn: 'കവിതയെ വിളിക്കുക',
      callDaughterSub: 'മകളോട് സംസാരിക്കുക',
      waterSub: 'വെള്ളം വേണം',
      foodSub: 'ഭക്ഷണം വേണം',
      medicineSub: 'മരുന്ന് വേണം',
      ambulance108Sub: '108 ആംബുലൻസ്',
      primaryTreatingCareTeam: 'ചികിത്സിക്കുന്ന മെഡിക്കൽ ടീം',
      treatmentForDesc: 'ചികിത്സ: ഉയർന്ന രക്തസമ്മർദ്ദം, മുട്ടുവേദന, പ്രമേഹം',
      viewFullMedicalReportBtn: 'പൂർണ്ണ മെഡിക്കൽ റിപ്പോർട്ട് കാണുക',
      doctorReportBtn: 'ഡോക്ടർ റിപ്പോർട്ട്',
    },
  },

  te: {
    medicalReport: {
      primaryIllness: [
        'అధిక రక్తపోటు (Stage 1 Essential Hypertension)',
        'మోకాలి కీళ్ళవాతం (Mild Bilateral Knee Osteoarthritis)',
        'టైప్ 2 మధుమేహం (Type 2 Diabetes Mellitus - HbA1c: 6.7%)',
      ],
      ongoingTreatments: [
        'టెల్మిసార్టన్ 40mg టాబ్లెట్ - ప్రతిరోజూ ఉదయం టిఫిన్ తర్వాత బీపీ నియంత్రణకు',
        'మెట్ఫార్మిన్ 500mg SR టాబ్లెట్ - ప్రతిరోజూ రాత్రి భోజనం తర్వాత షుగర్ నియంత్రణకు',
        'గ్లూకోసమైన్ సల్ఫేట్ 500mg + కాల్షియం D3 - కీళ్ల నొప్పుల నివారణ మరియు ఎముకల బలానికి',
        'రోజుకు 20 నిమిషాల వాకింగ్ మరియు ఉప్పు తక్కువగా ఉండే ఆహార నియమావళి',
      ],
      hospitalName: 'అపోలో హాస్పిటల్స్, గ్రీమ్స్ రోడ్, చెన్నై',
      hospitalAddress: '21 గ్రీమ్స్ లేన్, థౌసండ్ లైట్స్, చెన్నై, తమిళనాడు 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'డాక్టర్ కె. సుందరం రామనాథన్, MD, DM',
      doctorSpecialty: 'సీనియర్ కన్సల్టెంట్ కార్డియాలజిస్ట్ & జెరియాట్రిక్ స్పెషలిస్ట్',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (కార్డియాలజీ & కిడ్నీ పరీక్ష)',
      bloodGroup: 'ఓ పాజిటివ్ (O+)',
      allergies: ['పెన్సిలిన్ మందులు (చర్మంపై దద్దుర్లు)', 'సల్ఫా యాంటీబయాటిక్స్'],
      insuranceProvider: 'స్టార్ హెల్త్ సీనియర్ సిటిజన్ రెడ్ కార్పెట్ హెల్త్ ఇన్సూరెన్స్',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (క్యాష్‌లెస్ హెల్ప్‌లైన్)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'టెల్మిసార్టన్ 40mg (Telmisartan)',
        dosage: '1 మాత్ర',
        time: '08:30 AM',
        instructions: 'ఉదయం టిఫిన్ తర్వాత · బీపీ నియంత్రణ',
        category: 'గుండె ఆరోగ్యం',
      },
      {
        id: 'MED-2',
        name: 'కాల్షియం కార్బోనేట్ + విటమిన్ D3',
        dosage: '1 మాత్ర',
        time: '01:00 PM',
        instructions: 'మధ్యాహ్న భోజనం తర్వాత · ఎముకల బలం',
        category: 'సప్లిమెంట్స్',
      },
      {
        id: 'MED-3',
        name: 'మెట్ఫార్మిన్ 500mg SR (Metformin)',
        dosage: '1 మాత్ర',
        time: '08:30 PM',
        instructions: 'రాత్రి భోజనం తర్వాత · షుగర్ నియంత్రణ',
        category: 'మధుమేహం',
      },
      {
        id: 'MED-4',
        name: 'గ్లూకోసమైన్ సల్ఫేట్ 500mg',
        dosage: '1 క్యాప్సూల్',
        time: '08:30 PM',
        instructions: 'రాత్రి భోజనం తర్వాత · కీళ్ల నొప్పుల ఉపశమనం',
        category: 'కీళ్ల సంరక్షణ',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'ఉదయం అల్పాహారం (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 ఇడ్లీలు, ఉప్పు తక్కువ సాంబార్, గోరువెచ్చని నీరు',
        notes: 'టిఫిన్ తర్వాత 20 నిమిషాలకు టెల్మిసార్టన్ 40mg వేసుకోండి',
      },
      {
        id: 'FOOD-2',
        mealName: 'మధ్యాహ్న భోజనం (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'బ్రౌన్ రైస్, సొరకాయ కూర, చారు (రసం), తాజా పెరుగు',
        notes: 'తక్కువ ఉప్పు, పీచు పదార్థం మరియు పొటాషియం సమృద్ధిగా ఉండే భోజనం',
      },
      {
        id: 'FOOD-3',
        mealName: 'సాయంత్రం స్నాక్స్ (Snacks)',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'ఉడకబెట్టిన గుగ్గిళ్ళు (శనగలు), అల్లం హెర్బల్ టీ',
        notes: 'తప్పనిసరిగా 1 గ్లాసు గోరువెచ్చని నీరు త్రాగండి',
      },
      {
        id: 'FOOD-4',
        mealName: 'రాత్రి భోజనం (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 మెత్తని గోధుమ చపాతీలు, పెసరపప్పు కూర, కీరదోసకాయ',
        notes: 'భోజనం తర్వాత మెట్ఫార్మిన్ & గ్లూకోసమైన్ మందులు వేసుకోండి',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'కవిత రామస్వామి',
        relationship: 'పెద్ద కుమార్తె (ప్రధాన సంరక్షకురాలు)',
        phone: '+91 98401 23456',
        address: 'తిరువాన్మియూర్, చెన్నై (3.2 కి.మీ)',
        notes: 'రోజూ సాయంత్రం వచ్చి మందులు, నిత్యావసరాలు చూసుకుంటారు.',
      },
      {
        id: 'FM-2',
        name: 'విఘ్నేష్ రామస్వామి',
        relationship: 'చిన్న కుమారుడు (ద్వితీయ సంరక్షకుడు)',
        phone: '+91 98840 87654',
        address: 'వేలచేరి, చెన్నై (6.8 కి.మీ)',
        notes: 'వారాంతపు ఆసుపత్రి మరియు అత్యవసర సాయానికి అందుబాటులో ఉంటారు.',
      },
      {
        id: 'FM-3',
        name: 'రాజేష్ కన్నన్',
        relationship: 'అల్లుడు',
        phone: '+91 97900 11223',
        address: 'చెన్నై',
        notes: 'రవాణా సౌకర్యాలను సమన్వయం చేస్తారు.',
      },
      {
        id: 'FM-4',
        name: 'అనన్య రాజేష్',
        relationship: 'మనవరాలు',
        phone: '+91 98400 99881',
        address: 'చెన్నై',
        notes: 'రోజూ మధ్యాహ్నం అరన్ ద్వారా నానమ్మతో మాట్లాడుతుంది.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 అత్యవసర అంబులెన్స్ సేవ (GVK-EMRI)',
        type: 'అంబులెన్స్',
        phone: '108',
        distance: '1.2 కి.మీ (అడయార్ డిపో)',
        address: 'అడయార్ డిపో దగ్గర, ఎల్.బి. రోడ్, చెన్నై',
      },
      {
        id: 'NE-2',
        name: 'ఫోర్టిస్ మలార్ హాస్పిటల్ 24/7 ఎమర్జెన్సీ',
        type: 'ఆసుపత్రి',
        phone: '044 4289 2222',
        distance: '900 మీటర్లు (2.5 నిమిషాలు)',
        address: 'గాంధీ నగర్, అడయార్, చెన్నై 600020',
      },
      {
        id: 'NE-3',
        name: 'అడయార్ పోలీస్ స్టేషన్ J-2',
        type: 'పోలీస్',
        phone: '044 2491 0352 / 112',
        distance: '1.4 కి.మీ',
        address: 'సర్దార్ పటేల్ రోడ్, అడయార్, చెన్నై',
      },
      {
        id: 'NE-4',
        name: 'శ్రీ ఎస్. కుమార్ (పొరుగువారు)',
        type: 'పొరుగు వాలంటీర్',
        phone: '+91 98403 11220',
        distance: '20 మీటర్లు (ఫ్లాట్ 2B)',
        address: 'లక్ష్మి నివాస్, అడయార్',
      },
    ],
    loginPage: {
      whoAreYou: 'మీరు ఎవరు? (పాత్రను ఎంచుకోండి)',
      seniorPatient: 'వృద్ధులు / రోగి',
      familyCaregiver: 'కుటుంబం / సంరక్షకులు',
      homeInCharge: 'ఇన్-ఛార్జ్ / అడ్మిన్',
      seniorLivingArrangement: 'వృద్ధుల నివాస ఏర్పాట్లు',
      careContext: 'సంరక్షణ సందర్భం',
      withFamily: {
        title: 'కుటుంబంతో',
        subtitle: '👨‍👩‍👧 పిల్లలతో కలిసి నివసిస్తున్నారు',
        desc: 'వృద్ధులు తమ కుమారుడు, కుమార్తె లేదా కుటుంబ సభ్యులతో కలిసి ఉంటారు.',
      },
      livingIndependently: {
        title: 'స్వతంత్రంగా',
        subtitle: '🏠 ఒంటరిగా స్వతంత్రంగా నివసిస్తున్నారు',
        desc: 'వృద్ధులు ఒంటరిగా ఉంటారు; అరన్ ద్వారా నిరంతర రిమోట్ పర్యవేక్షణ ఉంటుంది.',
      },
      withRelatives: {
        title: 'బంధువులతో',
        subtitle: '👥 బంధువులతో కలిసి నివసిస్తున్నారు',
        desc: 'వృద్ధులు బంధువులు లేదా తోబుట్టువుల వద్ద ఉంటారు.',
      },
      withPartner: {
        title: 'భాగస్వామితో',
        subtitle: '❤️ జీవిత భాగస్వామితో నివసిస్తున్నారు',
        desc: 'వృద్ధులు తమ వృద్ధ భార్య/భర్తతో కలిసి ఉంటారు.',
      },
      authTitle: 'లాగిన్ ధృవీకరణ',
      mobileOption: 'మొబైల్ నంబర్',
      emailOption: 'ఇమెయిల్',
      mobileLabel: 'మొబైల్ ఫోన్ నంబర్',
      emailLabel: 'ఇమెయిల్ చిరునామా',
      passwordOtpLabel: 'పాస్‌వర్డ్ / ఓటీపీ',
      loginViaOtp: 'OTP ద్వారా లాగిన్ అవ్వండి',
      usePassword: 'పాస్‌వర్డ్ ఉపయోగించండి',
      enterOtpPlaceholder: '6 అంకెల OTP నమోదు చేయండి',
      loginBtn: 'అరన్ కేర్‌లో లాగిన్ అవ్వండి',
      instantDemoTitle: 'లైవ్ డెమో',
      continueDemoBtn: 'డెమో కొనసాగించండి (లక్ష్మి & కవిత)',
      createAccountBtn: '+ కొత్త ఖాతా తెరవండి & సెటప్ చేయండి',
      privacy: 'గోప్యతా విధానం',
      terms: 'సేవా నిబంధనలు',
      forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
      languageSelectLabel: 'యాప్ భాష ఎంచుకోండి / Select Language:',
    },
    seniorView: {
      goodMorningGreeting: 'శుభోదయం',
      howAreYouFeeling: 'మీరు ప్రస్తుతం ఎలా ఉన్నారు?',
      monitoringComfortDesc: 'అరన్ మీ ఆరోగ్యం, రక్తపోటు, మందులు మరియు నీటి సమయాలను పర్యవేక్షిస్తుంది.',
      morningCheckinTitle: 'ఉదయపు చెక్-ఇన్',
      checkinCompletedBadge: '✓ ఈరోజు ఉదయం 08:04 గంటలకు పూర్తయింది',
      checkinDueBadge: 'చెక్-ఇన్ సమయం అయ్యింది',
      nextCheckinTime: 'తదుపరి చెక్-ఇన్: సాయంత్రం 06:00 గంటలకు',
      imOkSubtitle: 'నేను బాగున్నాను · చెక్-ఇన్ నిర్ధారణ',
      needHelpSubtitle: 'నీరు, భోజనం, మందులు లేదా కుటుంబ సహాయం',
      talkToAranSubtitle: 'అరన్‌తో మీ భాషలో మాట్లాడండి',
      sosSubtitle: '112 అత్యవసరం, 108 అంబులెన్స్ మరియు కుటుంబ అలర్ట్',
      bpTargetNote: 'డాక్టర్ సుందరం లక్ష్యం: <130/85',
      drinkOneGlassBtn: '+ 1 గ్లాసు నీరు త్రాగాను (250ml)',
      waterLoggedToast: '1 గ్లాసు నీరు త్రాగినట్లు నమోదైంది.',
      checkinSuccessToast: 'ధన్యవాదాలు లక్ష్మమ్మ గారూ! మీ చెక్-ఇన్ నమోదైంది.',
      heatWarningTitle: 'గది వేడి హెచ్చరిక',
      heatWarningBanner: 'గది చాలా వేడిగా ఉంది. దయచేసి ఫ్యాన్ వేసుకుని నీరు త్రాగండి.',
      heatWarningAction: 'నీరు త్రాగండి',
      ambulance108DispatchedTitle: '108 అంబులెన్స్ బయలుదేరింది',
      ambulance108DispatchedDesc: 'మీ ఇంటికి వస్తోంది. చేరుకునే సమయం: 6 నిమిషాలు.',
      whatDoYouNeedTitle: 'మీకు ప్రస్తుతం ఏ సహాయం కావాలి?',
      whatDoYouNeedSubtitle: 'క్రింది బటన్‌ను నొక్కండి. అరన్ వెంటనే మీ కుమార్తెకు తెలియజేస్తుంది.',
      callDaughterBtn: 'కవితకు కాల్ చేయండి',
      callDaughterSub: 'కుమార్తెతో మాట్లాడండి',
      waterSub: 'మంచినీరు కావాలి',
      foodSub: 'ఆహారం కావాలి',
      medicineSub: 'మందులు కావాలి',
      ambulance108Sub: '108 అంబులెన్స్',
      primaryTreatingCareTeam: 'ప్రాథమిక చికిత్స వైద్యుల బృందం',
      treatmentForDesc: 'చికిత్స: అధిక రక్తపోటు, కీళ్ల నొప్పులు, మధుమేహ నియంత్రణ',
      viewFullMedicalReportBtn: 'పూర్తి ఆరోగ్య నివేదిక చూడండి',
      doctorReportBtn: 'వైద్య నివేదిక',
    },
  },

  kn: {
    medicalReport: {
      primaryIllness: [
        'ಅಧಿಕ ರಕ್ತದೊತ್ತಡ (Stage 1 Essential Hypertension)',
        'ಮಂಡಿ ಕೀಲು ಸವೆತ (Mild Bilateral Knee Osteoarthritis)',
        'ಟೈಪ್ 2 ಮಧುಮೇಹ (Type 2 Diabetes Mellitus - HbA1c: 6.7%)',
      ],
      ongoingTreatments: [
        'ಟೆಲ್ಮಿಸಾರ್ಟನ್ 40mg ಮಾತ್ರೆ - ರಕ್ತದೊತ್ತಡ ನಿಯಂತ್ರಣಕ್ಕಾಗಿ ಪ್ರತಿದಿನ ಬೆಳಗಿನ ಉಪಾಹಾರದ ನಂತರ',
        'ಮೆಟ್‌ಫಾರ್ಮಿನ್ 500mg SR ಮಾತ್ರೆ - ರಕ್ತದಲ್ಲಿನ ಸಕ್ಕರೆ ನಿಯಂತ್ರಣಕ್ಕಾಗಿ ರಾತ್ರಿಯ ಊಟದ ನಂತರ',
        'ಗ್ಲುಕೋಸಮೈನ್ ಸಲ್ಫೇಟ್ 500mg + ಕ್ಯಾಲ್ಸಿಯಂ D3 - ಕೀಲು ನೋವು ಶಮನ ಮತ್ತು ಮೂಳೆಗಳ ಬಲವರ್ಧನೆಗೆ',
        'ಪ್ರತಿದಿನ 20 ನಿಮಿಷಗಳ ನಡಿಗೆ ಮತ್ತು ಕಡಿಮೆ ಉಪ್ಪಿನ ಪಥ್ಯಾಹಾರ',
      ],
      hospitalName: 'ಅಪೋಲೋ ಹಾಸ್ಪಿಟಲ್ಸ್, ಗ್ರೀಮ್ಸ್ ರೋಡ್, ಚೆನ್ನೈ',
      hospitalAddress: '21 ಗ್ರೀಮ್ಸ್ ಲೇನ್, ಥೌಸಂಡ್ ಲೈಟ್ಸ್, ಚೆನ್ನೈ 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'ಡಾ. ಸುಂದರಂ ರಾಮನಾಥನ್, MD, DM',
      doctorSpecialty: 'ಹಿರಿಯ ಹೃದ್ರೋಗ ಮತ್ತು ವೃದ್ಧಾಪ್ಯ ರೋಗ ತಜ್ಞರು',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (ಕಾರ್ಡಿಯಾಲಜಿ & ಮೂತ್ರಪಿಂಡ ಪರೀಕ್ಷೆ)',
      bloodGroup: 'ಓ ಪಾಸಿಟಿವ್ (O+)',
      allergies: ['ಪೆನ್ಸಿಲಿನ್ ಔಷಧಿಗಳು', 'ಸಲ್ಫಾ ಆಂಟಿಬಯೋಟಿಕ್ಸ್'],
      insuranceProvider: 'ಸ್ಟಾರ್ ಹೆಲ್ತ್ ಸೀನಿಯರ್ ಸಿಟಿಜನ್ ರೆಡ್ ಕಾರ್ಪೆಟ್ ವಿಮೆ',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (ಕ್ಯಾಶ್‌ಲೆಸ್ ಡೆಸ್ಕ್)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'ಟೆಲ್ಮಿಸಾರ್ಟನ್ 40mg (Telmisartan)',
        dosage: '1 ಮಾತ್ರೆ',
        time: '08:30 AM',
        instructions: 'ಬೆಳಗಿನ ಉಪಾಹಾರದ ನಂತರ · ಬಿಪಿ ನಿಯಂತ್ರಣ',
        category: 'ಹೃದಯದ ಆರೋಗ್ಯ',
      },
      {
        id: 'MED-2',
        name: 'ಕ್ಯಾಲ್ಸಿಯಂ ಕಾರ್ಬೋನೇಟ್ + ವಿಟಮಿನ್ D3',
        dosage: '1 ಮಾತ್ರೆ',
        time: '01:00 PM',
        instructions: 'ಮಧ್ಯಾಹ್ನದ ಊಟದ ನಂತರ · ಮೂಳೆಗಳ ಬಲವರ್ಧನೆ',
        category: 'ಪೂರಕ ಔಷಧಿ',
      },
      {
        id: 'MED-3',
        name: 'ಮೆಟ್‌ಫಾರ್ಮಿನ್ 500mg SR (Metformin)',
        dosage: '1 ಮಾತ್ರೆ',
        time: '08:30 PM',
        instructions: 'ರಾತ್ರಿಯ ಊಟದ ನಂತರ · ಸಕ್ಕರೆ ನಿಯಂತ್ರಣ',
        category: 'ಮಧುಮೇಹ',
      },
      {
        id: 'MED-4',
        name: 'ಗ್ಲುಕೋಸಮೈನ್ ಸಲ್ಫೇಟ್ 500mg',
        dosage: '1 ಕ್ಯಾಪ್ಸೂಲ್',
        time: '08:30 PM',
        instructions: 'ರಾತ್ರಿಯ ಊಟದ ನಂತರ · ಕೀಲು ನೋವು ನಿವಾರಣೆ',
        category: 'ಕೀಲುಗಳ ಆರೈಕೆ',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'ಬೆಳಗಿನ ಉಪಾಹಾರ (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 ಇಡ್ಲಿ, ಕಡಿಮೆ ಉಪ್ಪಿನ ಸಾಂಬಾರ್, ಬೆಚ್ಚಗಿನ ನೀರು',
        notes: 'ಉಪಾಹಾರದ ನಂತರ ಟೆಲ್ಮಿಸಾರ್ಟನ್ 40mg ಮಾತ್ರೆ ಸೇವಿಸಿ',
      },
      {
        id: 'FOOD-2',
        mealName: 'ಮಧ್ಯಾಹ್ನದ ಊಟ (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'ಕುಚಲಕ್ಕಿ ಅನ್ನ, ಸೋರೆಕಾಯಿ ಪಲ್ಯ, ರಸಂ, ತಾಜಾ ಮೊಸರು',
        notes: 'ಕಡಿಮೆ ಉಪ್ಪು, ನಾರಿನಂಶ ಮತ್ತು ಪೊಟ್ಯಾಸಿಯಂ ಸಮೃದ್ಧ ಆಹಾರ',
      },
      {
        id: 'FOOD-3',
        mealName: 'ಸಂಜೆ ತಿಂಡಿ (Snacks)',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'ಬೇಯಿಸಿದ ಕಡಲೆ ಉಸಳಿ, ಶುಂಠಿ-ಏಲಕ್ಕಿ ಗಿಡಮೂಲಿಕೆ ಚಹಾ',
        notes: '1 ಲೋಟ ನೀರು ತಪ್ಪದೇ ಕುಡಿಯಿರಿ',
      },
      {
        id: 'FOOD-4',
        mealName: 'ರಾತ್ರಿಯ ಊಟ (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 ಮೃದುವಾದ ಗೋಧಿ ಚಪಾತಿ, ಹೆಸರುಬೇಳೆ ದಾಲ್, ಸೌತೆಕಾಯಿ ಸಲಾಡ್',
        notes: 'ಊಟದ ನಂತರ ಮೆಟ್‌ಫಾರ್ಮಿನ್ & ಗ್ಲುಕೋಸಮೈನ್ ಮಾತ್ರೆ ಸೇವಿಸಿ',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'ಕವಿತಾ ರಾಮಸ್ವಾಮಿ',
        relationship: 'ಹಿರಿಯ ಮಗಳು (ಮುಖ್ಯ ಆರೈಕೆದಾರರು)',
        phone: '+91 98401 23456',
        address: 'ತಿರುವನ್ಮಿಯೂರು, ಚೆನ್ನೈ (3.2 ಕಿ.ಮೀ)',
        notes: 'ಪ್ರತಿದಿನ ಸಂಜೆ ಭೇಟಿ ನೀಡಿ ಔಷಧಿ ಮತ್ತು ಅಗತ್ಯ ವಸ್ತುಗಳನ್ನು ನೋಡಿಕೊಳ್ಳುತ್ತಾರೆ.',
      },
      {
        id: 'FM-2',
        name: 'ವಿಘ್ನೇಶ್ ರಾಮಸ್ವಾಮಿ',
        relationship: 'ಕಿರಿಯ ಮಗ (ದ್ವಿತೀಯ ಆರೈಕೆದಾರರು)',
        phone: '+91 98840 87654',
        address: 'ವೇಲಾಚೇರಿ, ಚೆನ್ನೈ (6.8 ಕಿ.ಮೀ)',
        notes: 'ವಾರಾಂತ್ಯದಲ್ಲಿ ಆಸ್ಪತ್ರೆ ಭೇಟಿ ಮತ್ತು ತುರ್ತು ನೆರವಿಗೆ ಸಿದ್ಧರಿರುತ್ತಾರೆ.',
      },
      {
        id: 'FM-3',
        name: 'ರಾಜೇಶ್ ಕಣ್ಣನ್',
        relationship: 'ಅಳಿಯ',
        phone: '+91 97900 11223',
        address: 'ಚೆನ್ನೈ',
        notes: 'ವಾಹನ ವ್ಯವಸ್ಥೆ ಕಲ್ಪಿಸುತ್ತಾರೆ.',
      },
      {
        id: 'FM-4',
        name: 'ಅನನ್ಯಾ ರಾಜೇಶ್',
        relationship: 'ಮೊಮ್ಮಗಳು',
        phone: '+91 98400 99881',
        address: 'ಚೆನ್ನೈ',
        notes: 'ಪ್ರತಿದಿನ ಅಜ್ಜಿಯೊಂದಿಗೆ ಅರಣ್ ಸಾಧನದ ಮೂಲಕ ಮಾತನಾಡುತ್ತಾಳೆ.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 ತುರ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್ ಸೇವೆ (GVK-EMRI)',
        type: 'ಆಂಬ್ಯುಲೆನ್ಸ್',
        phone: '108',
        distance: '1.2 ಕಿ.ಮೀ (ಅಡ್ಯಾರ್)',
        address: 'ಅಡ್ಯಾರ್ ಡಿಪೋ ಹತ್ತಿರ, ಚೆನ್ನೈ',
      },
      {
        id: 'NE-2',
        name: 'ಫೋರ್ಟಿಸ್ ಮಲಾರ್ ಆಸ್ಪತ್ರೆ 24/7 ತುರ್ತು ಘಟಕ',
        type: 'ಆಸ್ಪತ್ರೆ',
        phone: '044 4289 2222',
        distance: '900 ಮೀಟರ್ (2.5 ನಿಮಿಷ)',
        address: 'ಗಾಂಧಿ ನಗರ, ಅಡ್ಯಾರ್, ಚೆನ್ನೈ',
      },
      {
        id: 'NE-3',
        name: 'ಅಡ್ಯಾರ್ ಪೊಲೀಸ್ ಠಾಣೆ J-2',
        type: 'ಪೊಲೀಸ್',
        phone: '044 2491 0352 / 112',
        distance: '1.4 ಕಿ.ಮೀ',
        address: 'ಸರ್ದಾರ್ ಪಟೇಲ್ ರಸ್ತೆ, ಅಡ್ಯಾರ್',
      },
      {
        id: 'NE-4',
        name: 'ಶ್ರೀ ಎಸ್. ಕುಮಾರ್ (ನೆರೆಹೊರೆಯವರು)',
        type: 'ನೆರೆಹೊರೆಯ ಸ್ವಯಂಸೇವಕರು',
        phone: '+91 98403 11220',
        distance: '20 ಮೀಟರ್ (ಫ್ಲಾಟ್ 2B)',
        address: 'ಲಕ್ಷ್ಮಿ ನಿವಾಸ್, ಅಡ್ಯಾರ್',
      },
    ],
    loginPage: {
      whoAreYou: 'ನೀವು ಯಾರು? (ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ)',
      seniorPatient: 'ಹಿರಿಯ ನಾಗರಿಕರು / ರೋಗಿ',
      familyCaregiver: 'ಕುಟುಂಬ / ಆರೈಕೆದಾರರು',
      homeInCharge: 'ಇನ್-ಚಾರ್ಜ್ / ನಿರ್ವಾಹಕರು',
      seniorLivingArrangement: 'ಹಿರಿಯರ ವಾಸಸ್ಥಳ ವ್ಯವಸ್ಥೆ',
      careContext: 'ಆರೈಕೆಯ ಸಂದರ್ಭ',
      withFamily: {
        title: 'ಕುಟುಂಬದೊಂದಿಗೆ',
        subtitle: '👨‍👩‍👧 ಮಕ್ಕಳೊಂದಿಗೆ ವಾಸಿಸುತ್ತಿದ್ದಾರೆ',
        desc: 'ಹಿರಿಯರು ತಮ್ಮ ಮಕ್ಕಳು ಅಥವಾ ಕುಟುಂಬ ಸದಸ್ಯರೊಂದಿಗೆ ಜತೆಯಾಗಿ ವಾಸಿಸುತ್ತಾರೆ.',
      },
      livingIndependently: {
        title: 'ಸ್ವತಂತ್ರವಾಗಿ',
        subtitle: '🏠 ಏಕಾಂಗಿಯಾಗಿ ವಾಸಿಸುತ್ತಿದ್ದಾರೆ',
        desc: 'ಹಿರಿಯರು ಸ್ವತಂತ್ರವಾಗಿ ವಾಸಿಸುತ್ತಾರೆ; ಅರಣ್ ನಿರಂತರ ಮೇಲ್ವಿಚಾರಣೆ ನಡೆಸುತ್ತದೆ.',
      },
      withRelatives: {
        title: 'ಸಂಬಂಧಿಕರೊಂದಿಗೆ',
        subtitle: '👥 ಸಂಬಂಧಿಕರ ಮನೆಯಲ್ಲಿದ್ದಾರೆ',
        desc: 'ಹಿರಿಯರು ಸಂಬಂಧಿಕರೊಂದಿಗೆ ಅಥವಾ ಸಹೋದರ-ಸಹೋದರಿಯರೊಂದಿಗೆ ವಾಸಿಸುತ್ತಾರೆ.',
      },
      withPartner: {
        title: 'ಜೀವನ ಸಂಗಾತಿಯೊಂದಿಗೆ',
        subtitle: '❤️ ಸಂಗಾತಿಯೊಂದಿಗೆ ವಾಸಿಸುತ್ತಿದ್ದಾರೆ',
        desc: 'ಹಿರಿಯರು ತಮ್ಮ ವಯಸ್ಸಾದ ಸಂಗಾತಿಯೊಂದಿಗೆ ವಾಸಿಸುತ್ತಾರೆ.',
      },
      authTitle: 'ದೃಢೀಕರಣ (Login)',
      mobileOption: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      emailOption: 'ಇಮೇಲ್',
      mobileLabel: 'ಮೊಬೈಲ್ ಫೋನ್ ಸಂಖ್ಯೆ',
      emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ',
      passwordOtpLabel: 'ಪಾಸ್‌ವರ್ಡ್ / ಒಟಿಪಿ',
      loginViaOtp: 'OTP ಮೂಲಕ ಲಾಗಿನ್ ಆಗಿ',
      usePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ',
      enterOtpPlaceholder: '6 ಅಂಕಿಗಳ OTP ನಮೂದಿಸಿ',
      loginBtn: 'ಅರಣ್ ಕೇರ್ ಲಾಗಿನ್ ಮಾಡಿ',
      instantDemoTitle: 'ತಕ್ಷಣದ ಲೈವ್ ಡೆಮೊ',
      continueDemoBtn: 'ಡೆಮೊ ಮುಂದುವರಿಸಿ (ಲಕ್ಷ್ಮಿ & ಕವಿತಾ)',
      createAccountBtn: '+ ಹೊಸ ಖಾತೆ ರಚಿಸಿ ಮತ್ತು ಸೆಟಪ್ ಮಾಡಿ',
      privacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
      terms: 'ಸೇವಾ ನಿಯಮಗಳು',
      forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
      languageSelectLabel: 'ಆ್ಯಪ್ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ / Select Language:',
    },
    seniorView: {
      goodMorningGreeting: 'ಶುಭೋದಯ',
      howAreYouFeeling: 'ನೀವು ಈಗ ಹೇಗಿದ್ದೀರಿ?',
      monitoringComfortDesc: 'ಅರಣ್ ನಿಮ್ಮ ಆರೋಗ್ಯ, ರಕ್ತದೊತ್ತಡ, ನೀರು ಮತ್ತು ಔಷಧಿಗಳ ವೇಳಾಪಟ್ಟಿಯನ್ನು ಗಮನಿಸುತ್ತಿದೆ.',
      morningCheckinTitle: 'ಬೆಳಗಿನ ಚೆಕ್-ಇನ್',
      checkinCompletedBadge: '✓ ಇಂದು ಬೆಳಿಗ್ಗೆ 08:04 ಕ್ಕೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
      checkinDueBadge: 'ಚೆಕ್-ಇನ್ ಸಮಯವಾಗಿದೆ',
      nextCheckinTime: 'ಮುಂದಿನ ಚೆಕ್-ಇನ್: ಸಂಜೆ 06:00 ಗಂಟೆಗೆ',
      imOkSubtitle: 'ನಾನು ಆರಾಮಾಗಿದ್ದೇನೆ · ಚೆಕ್-ಇನ್ ದೃಢೀಕರಣ',
      needHelpSubtitle: 'ನೀರು, ಊಟ, ಔಷಧಿ ಅಥವಾ ಕುಟುಂಬದ ನೆರವು',
      talkToAranSubtitle: 'ಅರಣ್ ಜೊತೆ ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ',
      sosSubtitle: '112 ತುರ್ತು ಕರೆ, 108 ಆಂಬ್ಯುಲೆನ್ಸ್ ಮತ್ತು ಕುಟುಂಬಕ್ಕೆ ಅಲರ್ಟ್',
      bpTargetNote: 'ಡಾ. ಸುಂದರಂ ಗುರಿ: <130/85',
      drinkOneGlassBtn: '+ 1 ಲೋಟ ನೀರು ಕುಡಿದೆ (250ml)',
      waterLoggedToast: '1 ಲೋಟ ನೀರು ಕುಡಿದದ್ದು ದಾಖಲಾಗಿದೆ.',
      checkinSuccessToast: 'ಧನ್ಯವಾದಗಳು ಲಕ್ಷ್ಮಮ್ಮನವರೇ! ನಿಮ್ಮ ಚೆಕ್-ಇನ್ ದಾಖಲಾಗಿದೆ.',
      heatWarningTitle: 'ಕೋಣೆಯ ಶಾಖದ ಎಚ್ಚರಿಕೆ',
      heatWarningBanner: 'ಕೋಣೆಯಲ್ಲಿ ಶಾಖ ಹೆಚ್ಚಾಗಿದೆ. ಫ್ಯಾನ್ ಹಾಕಿ, ನೀರು ಕುಡಿಯಿರಿ.',
      heatWarningAction: 'ನೀರು ಕುಡಿಯಿರಿ',
      ambulance108DispatchedTitle: '108 ಆಂಬ್ಯುಲೆನ್ಸ್ ಹೊರಟಿದೆ',
      ambulance108DispatchedDesc: 'ನಿಮ್ಮ ಮನೆಗೆ ಬರುತ್ತಿದೆ. ತಲುಪುವ ಸಮಯ: 6 ನಿಮಿಷಗಳು.',
      whatDoYouNeedTitle: 'ನಿಮಗೆ ಈಗ ಏನು ಸಹಾಯ ಬೇಕು?',
      whatDoYouNeedSubtitle: 'ಕೆಳಗಿನ ಯಾವುದಾದರೂ ಬಟನ್ ಒತ್ತಿ. ಅರಣ್ ತಕ್ಷಣ ನಿಮ್ಮ ಮಗಳಿಗೆ ತಿಳಿಸುತ್ತದೆ.',
      callDaughterBtn: 'ಕವಿತಾಗೆ ಕರೆ ಮಾಡಿ',
      callDaughterSub: 'ಮಗಳ ಜೊತೆ ಮಾತನಾಡಿ',
      waterSub: 'ನೀರು ಬೇಕು',
      foodSub: 'ಊಟ ಬೇಕು',
      medicineSub: 'ಮಾತ್ರೆ ಬೇಕು',
      ambulance108Sub: '108 ಆಂಬ್ಯುಲೆನ್ಸ್',
      primaryTreatingCareTeam: 'ಪ್ರಾಥಮಿಕ ಚಿಕಿತ್ಸಾ ವೈದ್ಯರ ತಂಡ',
      treatmentForDesc: 'ಚಿಕಿತ್ಸೆ: ಅಧಿಕ ರಕ್ತದೊತ್ತಡ, ಕೀಲು ನೋವು, ಮಧುಮೇಹ ನಿರ್ವಹಣೆ',
      viewFullMedicalReportBtn: 'ಸಂಪೂರ್ಣ ವೈದ್ಯಕೀಯ ವರದಿ ವೀಕ್ಷಿಸಿ',
      doctorReportBtn: 'ವೈದ್ಯರ ವರದಿ',
    },
  },

  gu: {
    medicalReport: {
      primaryIllness: [
        'હાઈ બ્લડ પ્રેશર (Stage 1 Essential Hypertension)',
        'ઢીંચણનો ઘસારો (Mild Bilateral Knee Osteoarthritis)',
        'ટાઈપ 2 ડાયાબિટીસ (Type 2 Diabetes Mellitus - HbA1c: 6.7%)',
      ],
      ongoingTreatments: [
        'ટેલ્મીસાર્ટન 40mg ગોળી - બ્લડ પ્રેશર નિયંત્રણ માટે રોજ સવારે નાસ્તા પછી',
        'મેટફોર્મિન 500mg SR ગોળી - ડાયાબિટીસ નિયંત્રણ માટે રોજ રાત્રિ ભોજન પછી',
        'ગ્લુકોસામાઈન 500mg + કેલ્શિયમ D3 - સાંધાના દુખાવામાં રાહત અને હાડકાની મજબૂતી માટે',
        'રોજ 20 મિનિટ સવારની ચાલવાની કસરત અને ઓછું મીઠું ધરાવતો વિશેષ આહાર',
      ],
      hospitalName: 'એપોલો હોસ્પિટલ્સ, ગ્રીમ્સ રોડ, ચેન્નાઈ',
      hospitalAddress: '21 ગ્રીમ્સ લેન, થાઉઝન્ડ લાઈટ્સ, ચેન્નાઈ 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'ડૉ. સુંદરમ રામનાથન, MD, DM',
      doctorSpecialty: 'સીનિયર કાર્ડિયોલોજિસ્ટ અને વૃદ્ધાવસ્થા તબીબી નિષ્ણાત',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (કાર્ડિયોલોજી અને કિડની તપાસ)',
      bloodGroup: 'ઓ પોઝિટિવ (O+)',
      allergies: ['પેનિસિલિન વર્ગની દવાઓ', 'સલ્ફા એન્ટિબાયોટિક્સ'],
      insuranceProvider: 'સ્ટાર હેલ્થ સિનિયર સિટીઝન રેડ કાર્પેટ હેલ્થ ઇન્સ્યોરન્સ',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (કેશલેસ હોસ્પિટલાઈઝેશન હેલ્પલાઇન)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'ટેલ્મીસાર્ટન 40mg (Telmisartan)',
        dosage: '1 ગોળી',
        time: '08:30 AM',
        instructions: 'સવારના નાસ્તા પછી · બીપી નિયંત્રણ',
        category: 'હૃદય સ્વાસ્થ્ય',
      },
      {
        id: 'MED-2',
        name: 'કેલ્શિયમ કાર્બોનેટ + વિટામિન D3',
        dosage: '1 ગોળી',
        time: '01:00 PM',
        instructions: 'બપોરના ભોજન પછી · હાડકાની મજબૂતી',
        category: 'સપ્લીમેન્ટ્સ',
      },
      {
        id: 'MED-3',
        name: 'મેટફોર્મિન 500mg SR (Metformin)',
        dosage: '1 ગોળી',
        time: '08:30 PM',
        instructions: 'રાત્રિ ભોજન પછી · ડાયાબિટીસ નિયંત્રણ',
        category: 'ડાયાબિટીસ',
      },
      {
        id: 'MED-4',
        name: 'ગ્લુકોસામાઈન સલ્ફેટ 500mg',
        dosage: '1 કેપ્સ્યુલ',
        time: '08:30 PM',
        instructions: 'રાત્રિ ભોજન પછી · સાંધાના દુખાવામાં રાહત',
        category: 'સાંધાની કાળજી',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'સવારનો નાસ્તો (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 ઇડલી, ઓછું મીઠું ધરાવતો સાંભાર, હૂંફાળું પાણી',
        notes: 'નાસ્તાના 20 મિનિટ પછી ટેલ્મીસાર્ટન 40mg ગોળી લો',
      },
      {
        id: 'FOOD-2',
        mealName: 'બપોરનું ભોજન (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'બ્રાઉન રાઇસ, દૂધીનું શાક, રસમ, તાજું દહીં',
        notes: 'ઓછું મીઠું, ફાઈબર અને પોટેશિયમયુક્ત આહાર',
      },
      {
        id: 'FOOD-3',
        mealName: 'સાંજનો નાસ્તો (Snacks)',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'બાફેલા ચણા (સુંડલ) અને આદુ-ઈલાયચીની હર્બલ ચા',
        notes: '1 ગ્લાસ ગરમ પાણી અચૂક પીવો',
      },
      {
        id: 'FOOD-4',
        mealName: 'રાત્રિ ભોજન (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 નરમ ઘઉંની રોટલી, મગની દાળ, કાકડીનું સલાડ',
        notes: 'ભોજન પછી મેટફોર્મિન અને ગ્લુકોસામાઈન ગોળી લો',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'કવિતા રામસ્વામી',
        relationship: 'મોટી દીકરી (મુખ્ય સંભાળ રાખનાર)',
        phone: '+91 98401 23456',
        address: 'તિરુવાનમિયૂર, ચેન્નાઈ (3.2 કિમી)',
        notes: 'રોજ સાંજે 6:30 વાગ્યે આવે છે. દવાઓ અને ઘરનો સામાન સંભાળે છે.',
      },
      {
        id: 'FM-2',
        name: 'વિઘ્નેશ રામસ્વામી',
        relationship: 'નાનો દીકરો (બીજો સંભાળ રાખનાર)',
        phone: '+91 98840 87654',
        address: 'વેલાચેરી, ચેન્નાઈ (6.8 કિમી)',
        notes: 'વીકએન્ડ હોસ્પિટલ વિઝિટ અને ઇમરજન્સીમાં મદદ કરે છે.',
      },
      {
        id: 'FM-3',
        name: 'રાજેશ કન્નન',
        relationship: 'જમાઈ',
        phone: '+91 97900 11223',
        address: 'ચેન્નાઈ',
        notes: 'વાહન અને હોસ્પિટલ પ્રવાસનું સંચાલન કરે છે.',
      },
      {
        id: 'FM-4',
        name: 'અનન્યા રાજેશ',
        relationship: 'પૌત્રી / દોહિત્રી',
        phone: '+91 98400 99881',
        address: 'ચેન્નાઈ',
        notes: 'રોજ બપોરે અરણ ડિવાઇસથી દાદી સાથે વાત કરે છે.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 ઇમરજન્સી એમ્બ્યુલન્સ સર્વિસ (GVK-EMRI)',
        type: 'એમ્બ્યુલન્સ',
        phone: '108',
        distance: '1.2 કિમી (અડયાર)',
        address: 'અડયાર ડેપો પાસે, એલ.બી. રોડ, ચેન્નાઈ',
      },
      {
        id: 'NE-2',
        name: 'ફોર્ટિસ મલાર હોસ્પિટલ 24/7 ઇમરજન્સી',
        type: 'હોસ્પિટલ',
        phone: '044 4289 2222',
        distance: '900 મીટર (2.5 મિનિટ)',
        address: 'ગાંધી નગર, અડયાર, ચેન્નાઈ 600020',
      },
      {
        id: 'NE-3',
        name: 'અડયાર પોલીસ સ્ટેશન J-2',
        type: 'પોલીસ',
        phone: '044 2491 0352 / 112',
        distance: '1.4 કિમી',
        address: 'સરદાર પટેલ રોડ, અડયાર',
      },
      {
        id: 'NE-4',
        name: 'શ્રી એસ. કુમાર (પડોશી)',
        type: 'પડોશી સ્વયંસેવક',
        phone: '+91 98403 11220',
        distance: '20 મીટર (ફ્લેટ 2B)',
        address: 'લક્ષ્મી નિવાસ, અડયાર',
      },
    ],
    loginPage: {
      whoAreYou: 'તમે કોણ છો? (રોલ પસંદ કરો)',
      seniorPatient: 'વરિષ્ઠ નાગરિક / દર્દી',
      familyCaregiver: 'પરિવાર / સંભાળ રાખનાર',
      homeInCharge: 'હોમ ઇન-ચાર્જ / એડમિન',
      seniorLivingArrangement: 'વરિષ્ઠ નાગરિક રહેઠાણ વ્યવસ્થા',
      careContext: 'સંભાળ સંદર્ભ',
      withFamily: {
        title: 'પરિવાર સાથે',
        subtitle: '👨‍👩‍👧 બાળકો સાથે રહે છે',
        desc: 'વડીલ પોતાના દીકરા, દીકરી કે પરિવાર સાથે રહે છે.',
      },
      livingIndependently: {
        title: 'સ્વતંત્ર રીતે',
        subtitle: '🏠 એકલા સ્વતંત્ર રહે છે',
        desc: 'વડીલ એકલા રહે છે; અરણ દ્વારા સતત દેખરેખ ચાલુ રહે છે.',
      },
      withRelatives: {
        title: 'સંબંધીઓ સાથે',
        subtitle: '👥 સંબંધીઓ સાથે રહે છે',
        desc: 'વડીલ સંબંધીઓ કે ભાઈ-બહેન સાથે રહે છે.',
      },
      withPartner: {
        title: 'જીવનસાથી સાથે',
        subtitle: '❤️ જીવનસાથી સાથે રહે છે',
        desc: 'વડીલ પોતાના વૃદ્ધ પતિ/પત્ની સાથે રહે છે.',
      },
      authTitle: 'પ્રમાણીકરણ (Login)',
      mobileOption: 'મોબાઈલ નંબર',
      emailOption: 'ઈમેલ',
      mobileLabel: 'મોબાઈલ ફોન નંબર',
      emailLabel: 'ઈમેલ એડ્રેસ',
      passwordOtpLabel: 'પાસવર્ડ / ઓટીપી',
      loginViaOtp: 'OTP દ્વારા લોગિન કરો',
      usePassword: 'પાસવર્ડ વાપરો',
      enterOtpPlaceholder: '6 અંકનો OTP દાખલ કરો',
      loginBtn: 'અરણ કેરમાં લૉગિન કરો',
      instantDemoTitle: 'લાઈવ ડેમો',
      continueDemoBtn: 'ડેમો ચાલુ રાખો (લક્ષ્મી અને કવિતા)',
      createAccountBtn: '+ નવું એકાઉન્ટ બનાવો અને સેટઅપ કરો',
      privacy: 'ગોપનીયતા નીતિ',
      terms: 'સેવાની શરતો',
      forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
      languageSelectLabel: 'ભાષા પસંદ કરો / Select Language:',
    },
    seniorView: {
      goodMorningGreeting: 'શુભ સવાર',
      howAreYouFeeling: 'તમે અત્યારે કેવું અનુભવો છો?',
      monitoringComfortDesc: 'અરણ તમારા સ્વાસ્થ્ય, બીપી, પાણી અને દવાઓનું સતત ધ્યાન રાખી રહ્યું છે.',
      morningCheckinTitle: 'સવારનું ચેક-ઇન',
      checkinCompletedBadge: '✓ આજે સવારે 08:04 વાગ્યે પૂર્ણ થયું',
      checkinDueBadge: 'ચેક-ઇનનો સમય થઈ ગયો છે',
      nextCheckinTime: 'આગામી ચેક-ઇન: સાંજે 06:00 વાગ્યે',
      imOkSubtitle: 'હું મજામાં છું · ચેક-ઇન પુષ્ટિ',
      needHelpSubtitle: 'પાણી, ખોરાક, દવા કે પરિવારની મદદ',
      talkToAranSubtitle: 'અરણ સાથે તમારી ભાષામાં વાત કરો',
      sosSubtitle: '112 ઇમરજન્સી, 108 એમ્બ્યુલન્સ અને પરિવારને એલર્ટ',
      bpTargetNote: 'ડૉ. સુંદરમ લક્ષ્ય: <130/85',
      drinkOneGlassBtn: '+ 1 ગ્લાસ પાણી પીધું (250ml)',
      waterLoggedToast: '1 ગ્લાસ પાણી પીધું તે નોંધાઈ ગયું.',
      checkinSuccessToast: 'આભાર લક્ષ્મીજી! તમારું ચેક-ઇન નોંધાઈ ગયું છે.',
      heatWarningTitle: 'ગરમીની ચેતવણી',
      heatWarningBanner: 'રૂમમાં ગરમી વધુ છે. કૃપા કરીને પંખો ચાલુ કરો અને પાણી પીઓ.',
      heatWarningAction: 'પાણી પીઓ',
      ambulance108DispatchedTitle: '108 એમ્બ્યુલન્સ રવાના થઈ ચૂકી છે',
      ambulance108DispatchedDesc: 'તમારા ઘર તરફ આવી રહી છે. પહોંચવાનો સમય: 6 મિનિટ.',
      whatDoYouNeedTitle: 'તમને અત્યારે શું મદદ જોઈએ છે?',
      whatDoYouNeedSubtitle: 'નીચે આપેલ બટન દબાવો. અરણ તરત જ તમારી દીકરીને જાણ કરશે.',
      callDaughterBtn: 'કવિતાને કૉલ કરો',
      callDaughterSub: 'દીકરી સાથે વાત કરો',
      waterSub: 'પાણી જોઈએ છે',
      foodSub: 'ભોજન જોઈએ છે',
      medicineSub: 'દવા જોઈએ છે',
      ambulance108Sub: '108 એમ્બ્યુલન્સ',
      primaryTreatingCareTeam: 'સારવાર કરતી મુખ્ય તબીબી ટીમ',
      treatmentForDesc: 'સારવાર: હાઈ બીપી, સાંધાનો દુખાવો, ડાયાબિટીસ નિયંત્રણ',
      viewFullMedicalReportBtn: 'સંપૂર્ણ હેલ્થ રિપોર્ટ જુઓ',
      doctorReportBtn: 'ડૉક્ટર રિપોર્ટ',
    },
  },

  fr: {
    medicalReport: {
      primaryIllness: [
        'Hypertension artérielle essentielle (Stade 1, sous traitement médicamenteux)',
        'Gonarthrose bilatérale légère (Arthrose dégénérative des genoux)',
        'Diabète de type 2 (HbA1c : 6,7 %, stabilisé par le régime et les antidiabétiques)',
      ],
      ongoingTreatments: [
        'Telmisartan 40 mg : 1 comprimé par jour le matin après le petit-déjeuner',
        'Metformine 500 mg LP : 1 comprimé le soir après le dîner pour la glycémie',
        'Sulfate de glucosamine 500 mg + Calcium & Vitamine D3 pour les articulations',
        'Marche quotidienne surveillée de 20 minutes et régime DASH pauvre en sel',
      ],
      hospitalName: 'Apollo Hospitals, Greams Road, Chennai',
      hospitalAddress: '21 Greams Lane, Thousand Lights, Chennai, Tamil Nadu 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'Dr K. Sundaram Ramanathan, MD, DM',
      doctorSpecialty: 'Cardiologue Référent & Spécialiste en Gériatrie',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (Bilan cardiologique et fonction rénale)',
      bloodGroup: 'O Positif (O+)',
      allergies: ['Groupe des pénicillines (éruptions cutanées)', 'Sulfamides'],
      insuranceProvider: 'Star Health Senior Citizen Red Carpet Assurance Santé',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (Assistance Prise en Charge)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'Telmisartan 40mg',
        dosage: '1 Comprimé',
        time: '08:30 AM',
        instructions: 'Après le petit-déjeuner · Régulation de la tension',
        category: 'Cardiovasculaire',
      },
      {
        id: 'MED-2',
        name: 'Carbonate de Calcium + Vitamine D3',
        dosage: '1 Comprimé',
        time: '01:00 PM',
        instructions: 'Après le déjeuner · Consolidation osseuse',
        category: 'Complément',
      },
      {
        id: 'MED-3',
        name: 'Metformine 500mg LP',
        dosage: '1 Comprimé',
        time: '08:30 PM',
        instructions: 'Après le dîner · Contrôle de la glycémie',
        category: 'Diabète',
      },
      {
        id: 'MED-4',
        name: 'Sulfate de Glucosamine 500mg',
        dosage: '1 Gélule',
        time: '08:30 PM',
        instructions: 'Après le dîner · Soulagement de larthrose',
        category: 'Articulations',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'Petit-déjeuner (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 Idlis vapeur, bouillon de légumes peu salé, eau tiède',
        notes: 'Prendre le Telmisartan 40mg 20 min après le repas',
      },
      {
        id: 'FOOD-2',
        mealName: 'Déjeuner Équilibré (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'Riz complet, légumes mijotés, soupe de lentilles rasam, yaourt frais',
        notes: 'Pauvre en sodium, riche en fibres et potassium',
      },
      {
        id: 'FOOD-3',
        mealName: 'Collation de lAprès-midi',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'Pois chiches cuits à la vapeur, infusion tisane gingembre',
        notes: 'Boire obligatoirement 1 verre deau tiède',
      },
      {
        id: 'FOOD-4',
        mealName: 'Dîner Léger (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 Galettes de blé souples, soupe de lentilles jaunes moong dal, salade de concombre',
        notes: 'Prendre la Metformine et la Glucosamine après le dîner',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'Kavitha Ramaswamy',
        relationship: 'Fille Aînée (Aidante Principale)',
        phone: '+91 98401 23456',
        address: 'Thiruvanmiyur, Chennai (3,2 km)',
        notes: 'Rend visite chaque soir à 18h30. Gère les médicaments et les courses.',
      },
      {
        id: 'FM-2',
        name: 'Vignesh Ramaswamy',
        relationship: 'Fils Cadet (Aidant Secondaire)',
        phone: '+91 98840 87654',
        address: 'Velachery, Chennai (6,8 km)',
        notes: 'Disponible pour les rendez-vous médicaux et urgences le week-end.',
      },
      {
        id: 'FM-3',
        name: 'Rajesh Kannan',
        relationship: 'Gendre',
        phone: '+91 97900 11223',
        address: 'Chennai',
        notes: 'Organise le transport médical et la logistique en véhicule.',
      },
      {
        id: 'FM-4',
        name: 'Ananya Rajesh',
        relationship: 'Petite-fille',
        phone: '+91 98400 99881',
        address: 'Chennai',
        notes: 'Parle avec sa grand-mère chaque après-midi via le boîtier ARAN.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: 'Ambulance dUrgence Publique 108 (GVK-EMRI)',
        type: 'Ambulance',
        phone: '108',
        distance: '1,2 km (Poste dAdyar)',
        address: 'Près du dépôt dAdyar, Lattice Bridge Road, Chennai',
      },
      {
        id: 'NE-2',
        name: 'Hôpital Fortis Malar - Service dUrgences 24/7',
        type: 'Hôpital',
        phone: '044 4289 2222',
        distance: '900 mètres (2,5 min de trajet)',
        address: 'Gandhi Nagar, Adyar, Chennai 600020',
      },
      {
        id: 'NE-3',
        name: 'Commissariat de Police Adyar J-2',
        type: 'Police',
        phone: '044 2491 0352 / 112',
        distance: '1,4 km',
        address: 'Sardar Patel Road, Adyar, Chennai',
      },
      {
        id: 'NE-4',
        name: 'M. S. Kumar (Voisin de Palier de Confiance)',
        type: 'Voisin Bénévole',
        phone: '+91 98403 11220',
        distance: '20 mètres (Appartement 2B, même étage)',
        address: 'Appartement 2B, Lakshmi Niwas, Adyar',
      },
    ],
    loginPage: {
      whoAreYou: 'Qui êtes-vous ? (Sélectionnez votre rôle)',
      seniorPatient: 'Senior / Patient',
      familyCaregiver: 'Famille / Proche Aidant',
      homeInCharge: 'Responsable Résidence / Admin',
      seniorLivingArrangement: 'Mode de Vie du Senior',
      careContext: 'Contexte de Suivi',
      withFamily: {
        title: 'EN FAMILLE',
        subtitle: '👨‍👩‍👧 Vit avec ses enfants / proches',
        desc: 'Le senior habite au domicile partagé avec ses enfants ou sa famille.',
      },
      livingIndependently: {
        title: 'EN AUTONOMIE',
        subtitle: '🏠 Vit seul(e) de manière autonome',
        desc: 'Le senior vit seul chez lui ; surveillance continue ARAN activée.',
      },
      withRelatives: {
        title: 'CHEZ DES PROCHES',
        subtitle: '👥 Vit avec des membres de sa parenté',
        desc: 'Le senior réside chez des neveux, nièces ou frères et sœurs.',
      },
      withPartner: {
        title: 'EN COUPLE',
        subtitle: '❤️ Vit avec son conjoint / sa conjointe',
        desc: 'Le senior vit avec son époux/épouse également âgé(e).',
      },
      authTitle: 'Authentification',
      mobileOption: 'Numéro de Mobile',
      emailOption: 'E-mail',
      mobileLabel: 'Numéro de Téléphone Mobile',
      emailLabel: 'Adresse E-mail',
      passwordOtpLabel: 'Mot de Passe / Code OTP',
      loginViaOtp: 'Connexion par code OTP',
      usePassword: 'Utiliser un mot de passe',
      enterOtpPlaceholder: 'Entrez le code OTP à 6 chiffres',
      loginBtn: 'CONNEXION À ARAN CARE',
      instantDemoTitle: 'Démonstration Immédiate',
      continueDemoBtn: 'CONTINUER COMME DÉMO (LAKSHMI & KAVITHA)',
      createAccountBtn: '+ Créer un Nouveau Compte Senior & Configuration',
      privacy: 'Politique de Confidentialité',
      terms: 'Conditions dUtilisation',
      forgotPassword: 'Mot de passe oublié ?',
      languageSelectLabel: 'Langue de lApplication / Select Language:',
    },
    seniorView: {
      goodMorningGreeting: 'Bonjour',
      howAreYouFeeling: 'Comment vous sentez-vous en ce moment ?',
      monitoringComfortDesc: 'ARAN veille sur votre confort, votre tension artérielle, votre hydratation et vos médicaments.',
      morningCheckinTitle: 'Pointage du Matin (Check-in)',
      checkinCompletedBadge: '✓ Validé aujourdhui à 08h04',
      checkinDueBadge: 'Pointage en attente',
      nextCheckinTime: 'Prochain pointage : 18h00 (Soir)',
      imOkSubtitle: 'Je vais bien · Confirmation du pointage',
      needHelpSubtitle: 'Eau, repas, médicament ou assistance proche',
      talkToAranSubtitle: 'Parler avec ARAN à la voix',
      sosSubtitle: 'Urgence 112, Ambulance 108 & alerte familiale',
      bpTargetNote: 'Objectif Dr Sundaram : <130/85',
      drinkOneGlassBtn: '+ 1 Verre dEau Bu (250ml)',
      waterLoggedToast: '1 Verre deau (+250ml) enregistré avec succès.',
      checkinSuccessToast: 'Merci Lakshmi ! Votre pointage a bien été enregistré.',
      heatWarningTitle: 'Alerte Canicule / Chaleur Ambiante',
      heatWarningBanner: 'La pièce est chaude. Veuillez allumer la ventilation et boire de leau.',
      heatWarningAction: 'Boire de lEau',
      ambulance108DispatchedTitle: 'AMBULANCE 108 DÉPÊCHÉE',
      ambulance108DispatchedDesc: 'En route vers votre domicile à Adyar. Arrivée estimée : 6 minutes.',
      whatDoYouNeedTitle: 'De quoi avez-vous besoin en ce moment ?',
      whatDoYouNeedSubtitle: 'Touchez un bouton ci-dessous. ARAN lenregistre et alerte votre fille Kavitha.',
      callDaughterBtn: 'Appeler Kavitha',
      callDaughterSub: 'Parler à sa fille',
      waterSub: 'Besoin dEau',
      foodSub: 'Besoin dAlimentation',
      medicineSub: 'Médicaments',
      ambulance108Sub: 'Ambulance 108',
      primaryTreatingCareTeam: 'Équipe Médicale Référente',
      treatmentForDesc: 'Suivi pour : Hypertension, Arthrose des genoux et Diabète',
      viewFullMedicalReportBtn: 'Voir le Bilan Médical Complet',
      doctorReportBtn: 'Bilan Médical',
    },
  },

  tanglish: {
    medicalReport: {
      primaryIllness: [
        'Blood Pressure / BP (Stage 1 Essential Hypertension - daily medicine management)',
        'Knee Joint Theimanam (Mild Bilateral Knee Osteoarthritis)',
        'Sugar / Diabetes (Type 2 Diabetes Mellitus - HbA1c: 6.7%)',
      ],
      ongoingTreatments: [
        'Telmisartan 40mg maathirai - Kaalai breakfast ku apram daily 1 tablet for BP control',
        'Metformin 500mg SR maathirai - Night dinner ku apram 1 tablet for sugar stability',
        'Glucosamine Sulfate 500mg + Calcium D3 - Knee joint pain relief and bone strength',
        'Daily 20 mins morning walking & low salt diet strictly recommended by doctor',
      ],
      hospitalName: 'Apollo Hospitals, Greams Road, Chennai',
      hospitalAddress: '21 Greams Lane, Thousand Lights, Chennai, Tamil Nadu 600006',
      hospitalEmergencyPhone: '044 2829 0200 / 1066',
      doctorName: 'Dr. Sundaram Ramanathan, MD, DM',
      doctorSpecialty: 'Senior Consultant Cardiologist & Senior Geriatric Specialist',
      doctorPhone: '+91 98410 55443',
      nextFollowUpDate: '2026-10-18 (Cardiology consultation & kidney test checkup)',
      bloodGroup: 'O Positive (O+)',
      allergies: ['Penicillin group medicines (causes skin rash)', 'Sulfa antibiotics'],
      insuranceProvider: 'Star Health Senior Citizen Red Carpet Health Insurance',
      policyNumber: 'SH-SC-8849201-CHN',
      tpaHelpline: '1800 425 2255 (Cashless Hospital Help Desk)',
    },
    medications: [
      {
        id: 'MED-1',
        name: 'Telmisartan 40mg',
        dosage: '1 Maathirai',
        time: '08:30 AM',
        instructions: 'Kaalai breakfast ku apram · BP Control',
        category: 'Cardiovascular',
      },
      {
        id: 'MED-2',
        name: 'Calcium Carbonate + Vit D3 (500mg)',
        dosage: '1 Maathirai',
        time: '01:00 PM',
        instructions: 'Lunch ku apram · Bone and joint strength',
        category: 'Supplements',
      },
      {
        id: 'MED-3',
        name: 'Metformin 500mg SR',
        dosage: '1 Maathirai',
        time: '08:30 PM',
        instructions: 'Night dinner ku apram · Sugar control',
        category: 'Endocrine',
      },
      {
        id: 'MED-4',
        name: 'Glucosamine Sulfate 500mg',
        dosage: '1 Capsule',
        time: '08:30 PM',
        instructions: 'Night dinner ku apram · Knee pain relief',
        category: 'Joint Care',
      },
    ],
    foodTimings: [
      {
        id: 'FOOD-1',
        mealName: 'Kaalai Tiffin (Breakfast)',
        scheduledTime: '08:00 AM',
        recommendedDiet: '2 Idlis, vegetable sambar with low salt, warm water',
        notes: 'Tiffin ku apram Telmisartan 40mg maathirai podunga',
      },
      {
        id: 'FOOD-2',
        mealName: 'Madhiya Saapaadu (Lunch)',
        scheduledTime: '12:30 PM',
        recommendedDiet: 'Brown rice, suraikai kootu, rasam, fresh curd',
        notes: 'Low salt, rich in dietary fiber & potassium',
      },
      {
        id: 'FOOD-3',
        mealName: 'Evening Snacks & Tea',
        scheduledTime: '04:30 PM',
        recommendedDiet: 'Boiled sundal (channa), warm herbal tea',
        notes: '1 glass warm water compulsory-aa kudinga',
      },
      {
        id: 'FOOD-4',
        mealName: 'Iravu Saapaadu (Dinner)',
        scheduledTime: '08:00 PM',
        recommendedDiet: '2 Soft wheat chapathis with dal & cucumber salad',
        notes: 'Dinner ku apram Metformin & Glucosamine maathirai podunga',
      },
    ],
    familyMembers: [
      {
        id: 'FM-1',
        name: 'Kavitha Ramaswamy',
        relationship: 'Mootha Magal (Primary Caregiver)',
        phone: '+91 98401 23456',
        address: 'Thiruvanmiyur, Chennai (3.2 km distance)',
        notes: 'Daily evening 6:30 ku vanthu paapanga. Medicines & groceries handle panranga.',
      },
      {
        id: 'FM-2',
        name: 'Vignesh Ramaswamy',
        relationship: 'Ilaya Magan (Secondary Caregiver)',
        phone: '+91 98840 87654',
        address: 'Velachery, Chennai (6.8 km distance)',
        notes: 'Weekend hospital trips and emergency ku immediate-aa varuvaaru.',
      },
      {
        id: 'FM-3',
        name: 'Rajesh Kannan',
        relationship: 'Marumagan (Son-in-law)',
        phone: '+91 97900 11223',
        address: 'Thiruvanmiyur, Chennai',
        notes: 'Car & hospital transport arrange pannuvaaru.',
      },
      {
        id: 'FM-4',
        name: 'Ananya Rajesh',
        relationship: 'Pethi (Granddaughter)',
        phone: '+91 98400 99881',
        address: 'Thiruvanmiyur, Chennai',
        notes: 'Daily afternoon paatti kooda ARAN video/audio la pesum.',
      },
    ],
    neighborhoodEmergencies: [
      {
        id: 'NE-1',
        name: '108 Tamil Nadu State Emergency Ambulance (GVK-EMRI)',
        type: 'Ambulance',
        phone: '108',
        distance: '1.2 km (Adyar Depot Station)',
        address: 'Near Adyar Depot, Lattice Bridge Road, Chennai',
      },
      {
        id: 'NE-2',
        name: 'Fortis Malar Hospital 24/7 Emergency Casualty',
        type: 'Hospital',
        phone: '044 4289 2222',
        distance: '900 meters (2.5 mins drive)',
        address: '52, 1st Main Rd, Gandhi Nagar, Adyar, Chennai 600020',
      },
      {
        id: 'NE-3',
        name: 'Adyar Police Station J-2',
        type: 'Police',
        phone: '044 2491 0352 / 112',
        distance: '1.4 km',
        address: 'Sardar Patel Road, Adyar, Chennai',
      },
      {
        id: 'NE-4',
        name: 'Mr. S. Kumar (Pakkathu Veedu Neighbor)',
        type: 'Neighborhood Volunteer',
        phone: '+91 98403 11220',
        distance: '20 meters (Flat 2B, same floor)',
        address: 'Lakshmi Niwas, 2nd Main Rd, Adyar',
      },
    ],
    loginPage: {
      whoAreYou: 'Neenga Yaaru? (Select Role)',
      seniorPatient: 'Senior / Patient',
      familyCaregiver: 'Family / Caregiver',
      homeInCharge: 'Home In-Charge / Admin',
      seniorLivingArrangement: 'Senior Living Arrangement',
      careContext: 'Care Context',
      withFamily: {
        title: 'WITH FAMILY',
        subtitle: '👨‍👩‍👧 Pillai kooda irukkanga',
        desc: 'Senior pillai, marumagal or family members kooda irukkanga.',
      },
      livingIndependently: {
        title: 'LIVING INDEPENDENTLY',
        subtitle: '🏠 Thaniyaaga irukkanga',
        desc: 'Senior thaniyaaga irukkanga; ARAN continuous monitoring on-la irukum.',
      },
      withRelatives: {
        title: 'WITH RELATIVES',
        subtitle: '👥 Uravinargal kooda',
        desc: 'Senior relatives veetula irukkanga.',
      },
      withPartner: {
        title: 'WITH PARTNER',
        subtitle: '❤️ Spouse kooda irukkanga',
        desc: 'Senior avanga spouse kooda jodiyaaga irukkanga.',
      },
      authTitle: 'Authentication',
      mobileOption: 'Mobile Number',
      emailOption: 'Email',
      mobileLabel: 'Mobile Phone Number',
      emailLabel: 'Email Address',
      passwordOtpLabel: 'Password / OTP',
      loginViaOtp: 'Login via OTP',
      usePassword: 'Password Use Panna',
      enterOtpPlaceholder: '6-digit OTP type pannunga',
      loginBtn: 'LOGIN TO ARAN CARE',
      instantDemoTitle: 'Instant Demo',
      continueDemoBtn: 'CONTINUE AS DEMO (LAKSHMI & KAVITHA)',
      createAccountBtn: '+ New Senior Account & Onboarding Create Panna',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      forgotPassword: 'Password Maranthuducha?',
      languageSelectLabel: 'App Language Select Pannunga / மொழி:',
    },
    seniorView: {
      goodMorningGreeting: 'Kaalai Vanakkam',
      howAreYouFeeling: 'Ippo eppadi irukkeenga? Are you feeling okay?',
      monitoringComfortDesc: 'ARAN unga health, BP rate, water intake and medicine schedule-ai paathukithu irukku.',
      morningCheckinTitle: 'Kaalai Check-In',
      checkinCompletedBadge: '✓ Innaiku kaalai 08:04 AM-ku done',
      checkinDueBadge: 'Check-in time aayiduchi',
      nextCheckinTime: 'Next Check-in: Evening 06:00 PM',
      imOkSubtitle: 'Naan nalla irukken · Morning check-in confirm panna',
      needHelpSubtitle: 'Thanni, saapaadu, maathirai or family help',
      talkToAranSubtitle: 'ARAN kitta Tamil & English-la pesunga',
      sosSubtitle: '112 Emergency, 108 Ambulance & family alert',
      bpTargetNote: 'Dr. Sundaram target: <130/85',
      drinkOneGlassBtn: '+ 1 Glass Thanni Kudithen (250ml)',
      waterLoggedToast: '1 Glass thanni (+250ml) note panniyaachu.',
      checkinSuccessToast: 'Super Lakshmi Amma! Unga check-in confirm aayiduchi.',
      heatWarningTitle: 'Room Heat Warning',
      heatWarningBanner: 'Room romba sooda irukku. Fan potu konjam thanni kudinga.',
      heatWarningAction: 'Thanni Kudikkavum',
      ambulance108DispatchedTitle: '108 AMBULANCE DISPATCH PANNIYAACHU',
      ambulance108DispatchedDesc: 'Unga Adyar veetuku vanthuttu irukku. ETA: 6 mins.',
      whatDoYouNeedTitle: 'Ungalukku ippo enna help venum?',
      whatDoYouNeedSubtitle: 'Keezhe ulla button-ai tap pannunga. ARAN Kavitha-ku alert anuppum.',
      callDaughterBtn: 'Kavitha-ku Call Panna',
      callDaughterSub: 'Magal kitta pesa',
      waterSub: 'Thanni Venum',
      foodSub: 'Saapaadu Venum',
      medicineSub: 'Maathirai Venum',
      ambulance108Sub: '108 Ambulance',
      primaryTreatingCareTeam: 'Treating Doctor & Hospital',
      treatmentForDesc: 'Treatment for: High BP, Knee Pain & Sugar Control',
      viewFullMedicalReportBtn: 'Full Medical Report Paakka',
      doctorReportBtn: 'Doctor Report',
    },
  },
};
